#pragma once

template <typename T1, typename T2>
struct compile_pair
{
	T1 first;
	T2 second;
};

namespace tables
{
	enum class eSessionType
	{
		JOIN_PUBLIC,
		NEW_PUBLIC,
		CLOSED_CREW,
		CREW,
		CLOSED_FRIENDS = 6,
		FIND_FRIEND = 9,
		SOLO,
		INVITE_ONLY,
		JOIN_CREW,
		SC_TV,
		LEAVE_ONLINE = -1
	};

	struct SessionType
	{
		eSessionType id;
		const char* name;
	};

	static constexpr auto sessions = std::to_array<SessionType>(
		{
			{eSessionType::JOIN_PUBLIC, "Find Public Session"},
			{eSessionType::NEW_PUBLIC, "Create Public Session"},
			{eSessionType::INVITE_ONLY, "Create Invite Only Session"},
			{eSessionType::CLOSED_FRIENDS, "Create Closed Friend Session"},
			{eSessionType::FIND_FRIEND, "Find Friend Session"},
			{eSessionType::CLOSED_CREW, "Create Closed Crew Session"},
			{eSessionType::CREW, "Find Crew Session"},
			{eSessionType::JOIN_CREW, "Join Crew Session"},
			{eSessionType::SOLO, "Create Solo Session"},
			{eSessionType::SC_TV, "Find Social Club TV Session"},
			{eSessionType::LEAVE_ONLINE, "Leave GTA Online"}
		});

	struct scenario
	{
		std::string_view m_label{};
		std::string_view m_key{};
	};

	inline constexpr scenario g_scenarios[]{
		//{ "Coffee", "WORLD_HUMAN_AA_COFFEE" },
		//{ "Smoke", "WORLD_HUMAN_AA_SMOKE" },
		{ "Binoculars", "WORLD_HUMAN_BINOCULARS" },
		//{ "Bum Freeway", "WORLD_HUMAN_BUM_FREEWAY" },
		{ "Bum Slumped", "WORLD_HUMAN_BUM_SLUMPED" },
		{ "Bum Standing", "WORLD_HUMAN_BUM_STANDING" },
		{ "Bum Wash", "WORLD_HUMAN_BUM_WASH" },
		{ "Car Park Attendant", "WORLD_HUMAN_CAR_PARK_ATTENDANT" },
		{ "Cheering", "WORLD_HUMAN_CHEERING" },
		//{ "Clipboard", "WORLD_HUMAN_CLIPBOARD" },
		{ "Construction Drill", "WORLD_HUMAN_CONST_DRILL" },
		{ "Idle Cop", "WORLD_HUMAN_COP_IDLES" },
		{ "Coffee", "WORLD_HUMAN_DRINKING" },
		//{ "Drug Dealer", "WORLD_HUMAN_DRUG_DEALER" },
		{ "Drug Dealer", "WORLD_HUMAN_DRUG_DEALER_HARD" },
		{ "Shocked Filming with Mobile ", "WORLD_HUMAN_MOBILE_FILM_SHOCKING" },
		{ "Leaf Blower", "WORLD_HUMAN_GARDENER_LEAF_BLOWER" },
		{ "Gardener Planting", "WORLD_HUMAN_GARDENER_PLANT" },
		{ "Golf Player", "WORLD_HUMAN_GOLF_PLAYER" },
		{ "Guard Patrol", "WORLD_HUMAN_GUARD_PATROL" },
		{ "Guard Standing", "WORLD_HUMAN_GUARD_STAND" },
		//{ "Guard Stand (Army)", "WORLD_HUMAN_GUARD_STAND_ARMY" },
		{ "Hammering", "WORLD_HUMAN_HAMMERING" },
		{ "Hang Out", "WORLD_HUMAN_HANG_OUT_STREET" },
		{ "Hiker Standing", "WORLD_HUMAN_HIKER_STANDING" },
		{ "Statue", "WORLD_HUMAN_HUMAN_STATUE" },
		{ "Janitor", "WORLD_HUMAN_JANITOR" },
		{ "Jogger Standing", "WORLD_HUMAN_JOG_STANDING" },
		{ "Leaning", "WORLD_HUMAN_LEANING" },
		{ "Cleaning", "WORLD_HUMAN_MAID_CLEAN" },
		{ "Muscle Flex", "WORLD_HUMAN_MUSCLE_FLEX" },
		{ "Free Weights", "WORLD_HUMAN_MUSCLE_FREE_WEIGHTS" },
		{ "Guitar", "WORLD_HUMAN_MUSICIAN" },
		{ "Paparazzi", "WORLD_HUMAN_PAPARAZZI" },
		//{ "Partying", "WORLD_HUMAN_PARTYING" },
		{ "Picnic", "WORLD_HUMAN_PICNIC" },
		{ "High Class Prostitute", "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS" },
		{ "Low Class Prostitute", "WORLD_HUMAN_PROSTITUTE_LOW_CLASS" },
		{ "Push Ups", "WORLD_HUMAN_PUSH_UPS" },
		{ "Seat Ledge", "WORLD_HUMAN_SEAT_LEDGE" },
		//{ "Seat Ledge (Eating)", "WORLD_HUMAN_SEAT_LEDGE_EATING" },
		{ "Seat Steps", "WORLD_HUMAN_SEAT_STEPS" },
		{ "Seat Wall", "WORLD_HUMAN_SEAT_WALL" },
		//{ "Seat Wall (Eating)", "WORLD_HUMAN_SEAT_WALL_EATING" },
		//{ "Seat Wall (Tablet)", "WORLD_HUMAN_SEAT_WALL_TABLET" },
		{ "Security Shining Torch", "WORLD_HUMAN_SECURITY_SHINE_TORCH" },
		{ "Sit Ups", "WORLD_HUMAN_SIT_UPS" },
		{ "Smoking", "WORLD_HUMAN_SMOKING" },
		//{ "Smoking Pot", "WORLD_HUMAN_SMOKING_POT" },
		{ "Warming Hands on Fire", "WORLD_HUMAN_STAND_FIRE" },
		{ "Fishing", "WORLD_HUMAN_STAND_FISHING" },
		{ "Impatient", "WORLD_HUMAN_STAND_IMPATIENT" },
		{ "Impatient (Upright)", "WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT" },
		{ "Mobile", "WORLD_HUMAN_STAND_MOBILE" },
		{ "Mobile (Upright)", "WORLD_HUMAN_STAND_MOBILE_UPRIGHT" },
		{ "Strip Watch", "WORLD_HUMAN_STRIP_WATCH_STAND" },
		{ "Stupor", "WORLD_HUMAN_STUPOR" },
		{ "Sunbathe", "WORLD_HUMAN_SUNBATHE" },
		{ "Sunbathe Back", "WORLD_HUMAN_SUNBATHE_BACK" },
		//{ "Superhero", "WORLD_HUMAN_SUPERHERO" },
		//{ "Swimming", "WORLD_HUMAN_SWIMMING" },
		{ "Tennis", "WORLD_HUMAN_TENNIS_PLAYER" },
		//{ "Tourist Map", "WORLD_HUMAN_TOURIST_MAP" },
		{ "Tourist Mobile", "WORLD_HUMAN_TOURIST_MOBILE" },
		{ "Vehicle Mechanic", "WORLD_HUMAN_VEHICLE_MECHANIC" },
		{ "Welding", "WORLD_HUMAN_WELDING" },
		{ "Window Shop Browse", "WORLD_HUMAN_WINDOW_SHOP_BROWSE" },
		{ "Yoga", "WORLD_HUMAN_YOGA" },
		{ "ATM", "PROP_HUMAN_ATM" },
		{ "BBQ", "PROP_HUMAN_BBQ" },
		{ "Bin", "PROP_HUMAN_BUM_BIN" },
		{ "Bum Shopping Cart", "PROP_HUMAN_BUM_SHOPPING_CART" },
		{ "Muscle Chin Ups", "PROP_HUMAN_MUSCLE_CHIN_UPS" },
		{ "Muscle Chin Ups (Army)", "PROP_HUMAN_MUSCLE_CHIN_UPS_ARMY" },
		{ "Muscle Chin Ups (Prison)", "PROP_HUMAN_MUSCLE_CHIN_UPS_PRISON" },
		{ "Parking Meter", "PROP_HUMAN_PARKING_METER" },
		{ "Seat Armchair", "PROP_HUMAN_SEAT_ARMCHAIR" },
		{ "Seat Bar", "PROP_HUMAN_SEAT_BAR" },
		{ "Seat Bench", "PROP_HUMAN_SEAT_BENCH" },
		{ "Seat Bench Drink", "PROP_HUMAN_SEAT_BENCH_DRINK" },
		{ "Seat Bench Drink Beer", "PROP_HUMAN_SEAT_BENCH_DRINK_BEER" },
		{ "Seat Bench Food", "PROP_HUMAN_SEAT_BENCH_FOOD" },
		{ "Seat Bus Stop Wait", "PROP_HUMAN_SEAT_BUS_STOP_WAIT" },
		{ "Seat Chair", "PROP_HUMAN_SEAT_CHAIR" },
		{ "Seat Chair Drink", "PROP_HUMAN_SEAT_CHAIR_DRINK" },
		{ "Seat Chair Drink Beer", "PROP_HUMAN_SEAT_CHAIR_DRINK_BEER" },
		{ "Seat Chair Food", "PROP_HUMAN_SEAT_CHAIR_FOOD" },
		{ "Seat Chair Upright", "PROP_HUMAN_SEAT_CHAIR_UPRIGHT" },
		{ "Seat Chair Multiplayer", "PROP_HUMAN_SEAT_CHAIR_MP_PLAYER" },
		{ "Seat Computer", "PROP_HUMAN_SEAT_COMPUTER" },
		{ "Seat Deckchair", "PROP_HUMAN_SEAT_DECKCHAIR" },
		{ "Seat Deckchair Drink", "PROP_HUMAN_SEAT_DECKCHAIR_DRINK" },
		{ "Seat Muscle Bench Press", "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS" },
		{ "Seat Muscle Bench Press (Prison)", "PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON" },
		{ "Seat Sewing", "PROP_HUMAN_SEAT_SEWING" },
		{ "Seat Strip Watch", "PROP_HUMAN_SEAT_STRIP_WATCH" },
		{ "Seat Sunlounger", "PROP_HUMAN_SEAT_SUNLOUNGER" },
		{ "Stand Impatient", "PROP_HUMAN_STAND_IMPATIENT" },
		{ "Cower", "CODE_HUMAN_COWER" },
		{ "Cross Road Wait", "CODE_HUMAN_CROSS_ROAD_WAIT" },
		{ "Park Car", "CODE_HUMAN_PARK_CAR" },
		{ "Movie Bulb Prop", "PROP_HUMAN_MOVIE_BULB" },
		{ "Movie Studio Light Prop", "PROP_HUMAN_MOVIE_STUDIO_LIGHT" },
		{ "Medic Kneel", "CODE_HUMAN_MEDIC_KNEEL" },
		{ "Tend to Dead", "CODE_HUMAN_MEDIC_TEND_TO_DEAD" },
		{ "Medic Time of Death", "CODE_HUMAN_MEDIC_TIME_OF_DEATH" },
		{ "Police Crowd Control", "CODE_HUMAN_POLICE_CROWD_CONTROL" },
		{ "Police Investigate", "CODE_HUMAN_POLICE_INVESTIGATE" },
		{ "Stand Cower", "CODE_HUMAN_STAND_COWER" },
		{ "Ear to Text", "EAR_TO_TEXT" },
		{ "Ear to Text (Fat)", "EAR_TO_TEXT_FAT" }
	};
	struct Casinowheel
	{
		int prize;
		const char* name;
	};
	static constexpr auto casinowheel = std::to_array<Casinowheel>(
		{
		{0,"Clothing 1"},
		{1,"RP 2,500"},
		{ 2,"Cash 20,000" },
		{ 3,"House Chips 10,000" },
		{ 4,"Discount Voucher" },
		{ 5,"RP 5,000" },
		{ 6,"Cash 30,000" },
		{ 7,"House Chips 15,000"},
		{ 8,"Clothing 2" },
		{ 9,"RP 7,500"},
		{ 10,"House Chips 20,000" },
		{ 11,"Mystery Star" },
		{ 12,"Clothing 3" },
		{ 13,"RP 10,000" },
		{ 14,"Cash 40,000", },
		{ 15,"House Chips 25,000"},
		{ 16,"Clothing 4"},
		{ 17,"RP 15,000" },
		{ 18,"Podium Vehicle" },
		{ 19,"Cash 50,000" }
		});
	struct wheel
	{
		int wheels;
		const char* name;
	};
	static constexpr auto wheels = std::to_array<wheel>(
		{
		{0,""},
		{1,"High end"},
		{ 2,"Lowrider" },
		{ 3,"Muscle" },
		{ 4,"Offroad" },
		{ 5,"Sport" },
		{ 6,"Suv" },
		{ 7,"Tuner"},
		{ 8,"Bike" },
		{ 9,"Benny's originals"},
		{ 10,"Benny's Bespoke" },
		{ 11,"Race" },
		{ 12,"Street" },
		{ 13,"Track" },
		});
	struct RegionType
	{
		uint32_t id;
		const char name[22];
	};
	static constexpr auto regions = std::to_array<RegionType>(
 {
		{0, "CIS"},
		{1, "South America"},
		{2, "US East"},
		{3, "Europe"},
		{4, "China"},
		{5, "Australia"},
		{6, "US West"},
		{7, "Japan"},
		{8, "Unknown"},
	    });
	inline constexpr scenario g_animal_scenarios[]
	{
		{ "Boar Grazing", "WORLD_BOAR_GRAZING" },
		{ "Cat Sleeping (Ground)", "WORLD_CAT_SLEEPING_GROUND" },
		{ "Cat Sleeping (Ledge)", "WORLD_CAT_SLEEPING_LEDGE" },
		{ "Cow Grazing", "WORLD_COW_GRAZING" },
		{ "Coyote Howl", "WORLD_COYOTE_HOWL" },
		{ "Coyote Rest", "WORLD_COYOTE_REST" },
		//{ "Coyote Wander", "WORLD_COYOTE_WANDER" },
		{ "Chickenhawk Feeding", "WORLD_CHICKENHAWK_FEEDING" },
		{ "Chickenhawk Standing", "WORLD_CHICKENHAWK_STANDING" },
		{ "Cormorant Standing", "WORLD_CORMORANT_STANDING" },
		{ "Crow Feeding", "WORLD_CROW_FEEDING" },
		{ "Crow Standing", "WORLD_CROW_STANDING" },
		{ "Deer Grazing", "WORLD_DEER_GRAZING" },
		{ "Rottweiler Barking", "WORLD_DOG_BARKING_ROTTWEILER" },
		{ "Retriever Barking", "WORLD_DOG_BARKING_RETRIEVER" },
		{ "Shepherd Barking", "WORLD_DOG_BARKING_SHEPHERD" },
		{ "Rottweiler Sitting", "WORLD_DOG_SITTING_ROTTWEILER" },
		{ "Retriever Sitting", "WORLD_DOG_SITTING_RETRIEVER" },
		{ "Shepherd Sitting", "WORLD_DOG_SITTING_SHEPHERD" },
		{ "Small Dog Barking", "WORLD_DOG_BARKING_SMALL" },
		{ "Small Dog Sitting", "WORLD_DOG_SITTING_SMALL" },
		//{ "Idle Fish", "WORLD_FISH_IDLE" },
		{ "Gull Feeding", "WORLD_GULL_FEEDING" },
		{ "Gull Standing", "WORLD_GULL_STANDING" },
		{ "Hen Pecking", "WORLD_HEN_PECKING" },
		{ "Hen Standing", "WORLD_HEN_STANDING" },
		{ "Mountain Lion Rest", "WORLD_MOUNTAIN_LION_REST" },
		//{ "Mountain Lion Wander", "WORLD_MOUNTAIN_LION_WANDER" },
		{ "Pig Grazing", "WORLD_PIG_GRAZING" },
		{ "Pigeon Feeding", "WORLD_PIGEON_FEEDING" },
		{ "Pigeon Standing", "WORLD_PIGEON_STANDING" },
		{ "Rabbit Eating", "WORLD_RABBIT_EATING" },
		{ "Rats Eating", "WORLD_RATS_EATING" },
		//{ "Shark Eating", "WORLD_SHARK_SWIM" },
		//{ "Bird in Tree", "PROP_BIRD_IN_TREE" },
		//{ "Bird Telegraph Pole", "PROP_BIRD_TELEGRAPH_POLE" },
	};

	struct animation
	{
		std::string_view label{};
		compile_pair<std::string_view, std::string_view> m_animation{};
	};

	inline constexpr animation g_sport_animations[]{
		{"Situps", {"amb@world_human_sit_ups@male@base", "base"}},
		{"Pushups", {"amb@world_human_push_ups@male@base", "base"}},
		{"Bench Press", {"amb@prop_human_seat_muscle_bench_press@idle_a", "idle_a"}},
		{"Pullups", {"SWITCH@FRANKLIN@GYM", "001942_02_GC_FRAS_IG_5_BASE"}},
		{"Chin Ups 1", {"amb@prop_human_muscle_chin_ups@male@base", "base"}},
		{"Chin Ups 2", {"amb@prop_human_muscle_chin_ups@male@enter", "enter"}},
		{"Chin Ups 3", {"amb@prop_human_muscle_chin_ups@male@exit", "exit_flee"}},
		{"Chin Ups 4", {"amb@prop_human_muscle_chin_ups@male@idle_a", "idle_a"}},
		{"Free Weights 1", {"amb@world_human_muscle_free_weights@male@barbell@base", "base"}},
		{"Free Weights 2", {"amb@world_human_muscle_free_weights@male@barbell@idle_a", "idle_a"}},
		{"Flex 1", {"amb@world_human_muscle_flex@arms_at_side@base", "base"}},
		{"Flex 2", {"amb@world_human_muscle_flex@arms_at_side@idle_a", "idle_a"}},
		{"Flex 3", {"amb@world_human_muscle_flex@arms_in_front@base", "base"}},
		{"Flex 4", {"amb@world_human_muscle_flex@arms_in_front@idle_a", "idle_b"}}
	};
	inline constexpr animation g_sex_animations[]{
		{"Pole Dance 1", {"mini@strip_club@pole_dance@pole_dance1", "pd_dance_01"}},
		{"Pole Dance 2", {"mini@strip_club@pole_dance@pole_dance2", "pd_dance_02"}},
		{"Pole Dance 3", {"mini@strip_club@pole_dance@pole_dance3", "pd_dance_03"}},
		{"Private Dance", {"mini@strip_club@private_dance@part1", "priv_dance_p1"}},
		{"Fuck 1", {"rcmpaparazzo_2", "shag_loop_a"}},
		{"Fuck 2", {"rcmpaparazzo_2", "shag_loop_poppy"}},
		{"Prostitue Sex (Male)", {"mini@prostitutes@sexnorm_veh", "sex_loop_male"}},
		{"Prostitue Sex (Female)", {"mini@prostitutes@sexnorm_veh", "sex_loop_prostitute"}},
		{"Prostitue BJ (Male)", {"mini@prostitutes@sexnorm_veh", "bj_loop_male"}},
		{"Prostitue BJ (Female)", {"mini@prostitutes@sexnorm_veh", "bj_loop_prostitute"}},
		{"Drunk Sex (Male)", {"random@drunk_driver_2", "cardrunksex_loop_m"}},
		{"Drunk Sex (Female)", {"random@drunk_driver_2", "cardrunksex_loop_f"}},
		{"Jerking Off", {"switch@trevor@jerking_off", "trev_jerking_off_loop"}}
	};
	inline constexpr animation g_dance_animations[]{
		{"High Center", {"anim@amb@casino@mini@dance@dance_solo@female@var_b@", "high_center"}},
		{"High Center Down", {"anim@amb@casino@mini@dance@dance_solo@female@var_b@", "high_center_down"}},
		{"Tap Dance", {"special_ped@mountain_dancer@monologue_2@monologue_2a", "mnt_dnc_angel"}},
		{"Buttwag Dance", {"special_ped@mountain_dancer@monologue_3@monologue_3a", "mnt_dnc_buttwag"}},
		{"Verse Dance", {"special_ped@mountain_dancer@monologue_4@monologue_4a", "mnt_dnc_verse"}},
		{"Heaven Dance", {"special_ped@mountain_dancer@monologue_1@monologue_1a", "mtn_dnc_if_you_want_to_get_to_heaven"}},
		{"Idle Clown", {"rcm_barry2", "clown_idle_6"}},
		{"Heaven Dance", {"special_ped@mountain_dancer@monologue_1@monologue_1a", "mtn_dnc_if_you_want_to_get_to_heaven"}},
	};
	inline constexpr animation g_super_hero_animations[]{
		{"I'm An Actor", {"special_ped@impotent_rage@convo_1@convo_1a", "im_an_actor_0"}},
		{"You Can't Stop Me", {"special_ped@impotent_rage@monologue_12@monologue_12d", "you_cant_stop_my_3"}},
		{"I Wanna Do Hamlet", {"special_ped@impotent_rage@convo_2@convo_2a", "i_wanna_do_hamlet_0"}},
		{"Having About As Much", {"special_ped@impotent_rage@convo_3@convo_3a", "having_about_as_much_0"}},
		{"Just Wondering When", {"special_ped@impotent_rage@convo_4@convo_4a", "just_woundering_when_0"}},
		{"Great I Wanted To", {"special_ped@impotent_rage@convo_5@convo_5a", "great_i_wanted_to_0"}},
		{"A Tourist Just Asked to", {"special_ped@impotent_rage@convo_6@convo_6a", "a_tourist_just_asked_0"}},
		{"Idle Intro", {"special_ped@impotent_rage@intro", "idle_intro"}},
		{"Defeat 1", {"special_ped@impotent_rage@monologue_10@monologue_10b", "i_will_defeat_the_1"}},
		{"Defeat 2", {"special_ped@impotent_rage@monologue_10@monologue_10c", "i_will_defeat_the_2"}},
		{"Unhappy 1", {"special_ped@impotent_rage@monologue_11@monologue_11a", "really_very_unhappy_0"}},
		{"Unhappy 2", {"special_ped@impotent_rage@monologue_11@monologue_11b", "really_very_unhappy_1"}},
		{"Unhappy 3", {"special_ped@impotent_rage@monologue_11@monologue_11c", "really_very_unhappy_2"}},
		{"Unhappy 4", {"special_ped@impotent_rage@monologue_11@monologue_11d", "really_very_unhappy_3"}}
	};
	inline constexpr animation g_miscellaneous_animations[]{
		{"Tazer", {"ragdoll@human", "electrocute"}},
		{"On Fire", {"ragdoll@human", "on_fire"}},
		{"Electrocute", {"stungun@standing", "damage"}},
		{"Waving Arms", {"random@car_thief@victimpoints_ig_3", "arms_waving"}},
		{"Meditating", {"rcmcollect_paperleadinout@", "meditiate_idle"}},
		{"Rolling Barrel", {"misschinese2_barrelroll", "barrel_roll_loop_A"}},
		{"Cop Kneeling Arrest", {"random@arrests", "kneeling_arrest_idle"}},
		{"Drunk Howling", {"switch@trevor@drunk_howling", "loop"}},
		{"Pee", {"p_airdancer_01_s", "peeing_intro"}},
		{"T-Pose", {"nm@hands", "hands_up"}}
	};
	inline constexpr uint32_t g_invalid_lod_models[3]{
		"slod_human"_joaat,
		"slod_large_quadped"_joaat,
		"slod_small_quadped"_joaat
	};
	inline constexpr uint32_t g_invalid_vehicle_models[5]{
		"arbitergt"_joaat,
		"astron2"_joaat,
		"cyclone2"_joaat,
		"ignus2"_joaat,
		"s95"_joaat
	};
	constexpr uint32_t g_invalid_objects[60]{
		"prop_dummy_01"_joaat,
		"prop_fragtest_cnst_02"_joaat,
		"prop_fragtest_cnst_03"_joaat,
		"prop_fragtest_cnst_04"_joaat,
		"prop_fragtest_cnst_05"_joaat,
		"prop_fragtest_cnst_06"_joaat,
		"prop_fragtest_cnst_06b"_joaat,
		"prop_fragtest_cnst_07"_joaat,
		"prop_fragtest_cnst_08"_joaat,
		"prop_fragtest_cnst_08b"_joaat,
		"prop_fragtest_cnst_08c"_joaat,
		"prop_fragtest_cnst_09"_joaat,
		"prop_fragtest_cnst_09b"_joaat,
		"prop_fragtest_cnst_10"_joaat,
		"prop_fragtest_cnst_11"_joaat,
		"prop_dummy_car"_joaat,
		"prop_dummy_light"_joaat,
		"prop_dummy_plane"_joaat,
		"prop_distantcar_night"_joaat,
		"prop_distantcar_day"_joaat,
		"hei_bh1_08_details4_em_night"_joaat,
		"dt1_18_sq_night_slod"_joaat,
		"ss1_12_night_slod"_joaat,
		"h4_prop_bush_bgnvla_med_01"_joaat,
		"h4_prop_bush_bgnvla_lrg_01"_joaat,
		"h4_prop_bush_buddleia_low_01"_joaat,
		"h4_prop_bush_ear_aa"_joaat,
		"h4_prop_bush_ear_ab"_joaat,
		"h4_prop_bush_fern_low_01"_joaat,
		"h4_prop_bush_fern_tall_cc"_joaat,
		"h4_prop_bush_mang_ad"_joaat,
		"h4_prop_bush_mang_low_aa"_joaat,
		"h4_prop_bush_mang_low_ab"_joaat,
		"h4_prop_bush_seagrape_low_01"_joaat,
		"prop_h4_ground_cover"_joaat,
		"h4_prop_weed_groundcover_01"_joaat,
		"h4_prop_grass_med_01"_joaat,
		"h4_prop_grass_tropical_lush_01"_joaat,
		"h4_prop_grass_wiregrass_01"_joaat,
		"h4_prop_weed_01_plant"_joaat,
		"h4_prop_weed_01_row"_joaat,
		"urbanweeds02_l1"_joaat,
		"proc_forest_grass01"_joaat,
		"prop_small_bushyba"_joaat,
		"v_res_d_dildo_a"_joaat,
		"v_res_d_dildo_b"_joaat,
		"v_res_d_dildo_c"_joaat,
		"v_res_d_dildo_d"_joaat,
		"v_res_d_dildo_e"_joaat,
		"v_res_d_dildo_f"_joaat,
		"v_res_skateboard"_joaat,
		"prop_battery_01"_joaat,
		"prop_barbell_01"_joaat,
		"prop_barbell_02"_joaat,
		"prop_bandsaw_01"_joaat,
		"prop_bbq_3"_joaat,
		"v_med_curtainsnewcloth2"_joaat,
		"bh1_07_flagpoles"_joaat,
		92962485
	};
	constexpr uint32_t g_model_blacklist[]{
		"apa_mp_apa_yacht_jacuzzi_ripple"_joaat,
		"apa_mp_apa_yacht_jacuzzi_ripple2"_joaat,
		"apa_mp_apa_yacht_jacuzzi_ripple003"_joaat,
		"prop_rub_cage01a"_joaat,
		"prop_fnclink_05crnr1"_joaat,
		"prop_gold_cont_01"_joaat,
		"prop_fnclink_02n"_joaat,
		"prop_fnclink_04g"_joaat,
		"prop_fnclink_09b"_joaat,
		"prop_feeder1"_joaat,
		"stt_prop_stunt_tube_s"_joaat,
		"prop_feeder1_cr"_joaat,
		"p_cablecar_s"_joaat,
	};

#pragma once

	const inline static std::vector<std::pair<int, const char*>> task_type_names = {
		{0, "CTaskHandsUp"},
		{1, "CTaskClimbLadder"},
		{2, "CTaskExitVehicle"},
		{3, "CTaskCombatRoll"},
		{4, "CTaskAimGunOnFoot"},
		{5, "CTaskMovePlayer"},
		{6, "CTaskPlayerOnFoot"},
		{8, "CTaskWeapon"},
		{9, "CTaskPlayerWeapon"},
		{10, "CTaskPlayerIdles"},
		{12, "CTaskAimGun"},
		{12, "CTaskComplex"},
		{12, "CTaskFSMClone"},
		{12, "CTaskMotionBase"},
		{12, "CTaskMove"},
		{12, "CTaskMoveBase"},
		{12, "CTaskNMBehaviour"},
		{12, "CTaskNavBase"},
		{12, "CTaskScenario"},
		{12, "CTaskSearchBase"},
		{12, "CTaskSearchInVehicleBase"},
		{12, "CTaskShockingEvent"},
		{12, "CTaskTrainBase"},
		{12, "CTaskVehicleFSM"},
		{12, "CTaskVehicleGoTo"},
		{12, "CTaskVehicleMissionBase"},
		{12, "CTaskVehicleTempAction"},
		{14, "CTaskPause"},
		{15, "CTaskDoNothing"},
		{16, "CTaskGetUp"},
		{17, "CTaskGetUpAndStandStill"},
		{18, "CTaskFallOver"},
		{19, "CTaskFallAndGetUp"},
		{20, "CTaskCrawl"},
		{25, "CTaskComplexOnFire"},
		{26, "CTaskDamageElectric"},
		{28, "CTaskTriggerLookAt"},
		{29, "CTaskClearLookAt"},
		{30, "CTaskSetCharDecisionMaker"},
		{31, "CTaskSetPedDefensiveArea"},
		{32, "CTaskUseSequence"},
		{34, "CTaskMoveStandStill"},
		{35, "CTaskComplexControlMovement"},
		{36, "CTaskMoveSequence"},
		{38, "CTaskAmbientClips"},
		{39, "CTaskMoveInAir"},
		{40, "CTaskNetworkClone"},
		{41, "CTaskUseClimbOnRoute"},
		{42, "CTaskUseDropDownOnRoute"},
		{43, "CTaskUseLadderOnRoute"},
		{44, "CTaskSetBlockingOfNonTemporaryEvents"},
		{45, "CTaskForceMotionState"},
		{46, "CTaskSlopeScramble"},
		{47, "CTaskGoToAndClimbLadder"},
		{48, "CTaskClimbLadderFully"},
		{49, "CTaskRappel"},
		{50, "CTaskVault"},
		{51, "CTaskDropDown"},
		{52, "CTaskAffectSecondaryBehaviour"},
		{53, "CTaskAmbientLookAtEvent"},
		{54, "CTaskOpenDoor"},
		{55, "CTaskShovePed"},
		{56, "CTaskSwapWeapon"},
		{57, "CTaskGeneralSweep"},
		{58, "CTaskPolice"},
		{59, "CTaskPoliceOrderResponse"},
		{60, "CTaskPursueCriminal"},
		{62, "CTaskArrestPed"},
		{63, "CTaskArrestPed2"},
		{64, "CTaskBusted"},
		{65, "CTaskFirePatrol"},
		{66, "CTaskHeliOrderResponse"},
		{67, "CTaskHeliPassengerRappel"},
		{68, "CTaskAmbulancePatrol"},
		{69, "CTaskPoliceWantedResponse"},
		{70, "CTaskSwat"},
		{72, "CTaskSwatWantedResponse"},
		{73, "CTaskSwatOrderResponse"},
		{74, "CTaskSwatGoToStagingArea"},
		{75, "CTaskSwatFollowInLine"},
		{76, "CTaskWitness"},
		{77, "CTaskGangPatrol"},
		{78, "CTaskArmy"},
		{80, "CTaskShockingEventWatch"},
		{82, "CTaskShockingEventGoto"},
		{83, "CTaskShockingEventHurryAway"},
		{84, "CTaskShockingEventReactToAircraft"},
		{85, "CTaskShockingEventReact"},
		{86, "CTaskShockingEventBackAway"},
		{87, "CTaskShockingPoliceInvestigate"},
		{88, "CTaskShockingEventStopAndStare"},
		{89, "CTaskShockingNiceCarPicture"},
		{90, "CTaskShockingEventThreatResponse"},
		{92, "CTaskTakeOffHelmet"},
		{93, "CTaskCarReactToVehicleCollision"},
		{95, "CTaskCarReactToVehicleCollisionGetOut"},
		{97, "CTaskDyingDead"},
		{100, "CTaskWanderingScenario"},
		{101, "CTaskWanderingInRadiusScenario"},
		{103, "CTaskMoveBetweenPointsScenario"},
		{104, "CTaskChatScenario"},
		{106, "CTaskCowerScenario"},
		{107, "CTaskDeadBodyScenario"},
		{114, "CTaskSayAudio"},
		{116, "CTaskWaitForSteppingOut"},
		{117, "CTaskCoupleScenario"},
		{118, "CTaskUseScenario"},
		{119, "CTaskUseVehicleScenario"},
		{120, "CTaskUnalerted"},
		{121, "CTaskStealVehicle"},
		{122, "CTaskReactToPursuit"},
		{125, "CTaskHitWall"},
		{126, "CTaskCower"},
		{127, "CTaskCrouch"},
		{128, "CTaskMelee"},
		{129, "CTaskMoveMeleeMovement"},
		{130, "CTaskMeleeActionResult"},
		{131, "CTaskMeleeUpperbodyAnims"},
		{133, "CTaskMoVEScripted"},
		{134, "CTaskScriptedAnimation"},
		{135, "CTaskSynchronizedScene"},
		{137, "CTaskComplexEvasiveStep"},
		{138, "CTaskWalkRoundCarWhileWandering"},
		{140, "CTaskComplexStuckInAir"},
		{141, "CTaskWalkRoundEntity"},
		{142, "CTaskMoveWalkRoundVehicle"},
		{144, "CTaskReactToGunAimedAt"},
		{146, "CTaskDuckAndCover"},
		{147, "CTaskAggressiveRubberneck"},
		{150, "CTaskInVehicleBasic"},
		{151, "CTaskCarDriveWander"},
		{152, "CTaskLeaveAnyCar"},
		{153, "CTaskComplexGetOffBoat"},
		{155, "CTaskCarSetTempAction"},
		{156, "CTaskBringVehicleToHalt"},
		{157, "CTaskCarDrive"},
		{159, "CTaskPlayerDrive"},
		{160, "CTaskEnterVehicle"},
		{161, "CTaskEnterVehicleAlign"},
		{162, "CTaskOpenVehicleDoorFromOutside"},
		{163, "CTaskEnterVehicleSeat"},
		{164, "CTaskCloseVehicleDoorFromInside"},
		{165, "CTaskInVehicleSeatShuffle"},
		{167, "CTaskExitVehicleSeat"},
		{168, "CTaskCloseVehicleDoorFromOutside"},
		{169, "CTaskControlVehicle"},
		{170, "CTaskMotionInAutomobile"},
		{171, "CTaskMotionOnBicycle"},
		{172, "CTaskMotionOnBicycleController"},
		{173, "CTaskMotionInVehicle"},
		{174, "CTaskMotionInTurret"},
		{175, "CTaskReactToBeingJacked"},
		{176, "CTaskReactToBeingAskedToLeaveVehicle"},
		{177, "CTaskTryToGrabVehicleDoor"},
		{178, "CTaskGetOnTrain"},
		{179, "CTaskGetOffTrain"},
		{180, "CTaskRideTrain"},
		{190, "CTaskMountThrowProjectile"},
		{195, "CTaskGoToCarDoorAndStandStill"},
		{196, "CTaskMoveGoToVehicleDoor"},
		{197, "CTaskSetPedInVehicle"},
		{198, "CTaskSetPedOutOfVehicle"},
		{199, "CTaskVehicleMountedWeapon"},
		{200, "CTaskVehicleGun"},
		{201, "CTaskVehicleProjectile"},
		{204, "CTaskSmashCarWindow"},
		{205, "CTaskMoveGoToPoint"},
		{206, "CTaskMoveAchieveHeading"},
		{207, "CTaskMoveFaceTarget"},
		{208, "CTaskComplexGoToPointAndStandStillTimed"},
		{208, "CTaskMoveGoToPointAndStandStill"},
		{209, "CTaskMoveFollowPointRoute"},
		{210, "CTaskMoveSeekEntity_CEntitySeekPosCalculatorStandard"},
		{211, "CTaskMoveSeekEntity_CEntitySeekPosCalculatorLastNavMeshIntersection"},
		{212, "CTaskMoveSeekEntity_CEntitySeekPosCalculatorLastNavMeshIntersection2"},
		{213, "CTaskMoveSeekEntity_CEntitySeekPosCalculatorXYOffsetFixed"},
		{214, "CTaskMoveSeekEntity_CEntitySeekPosCalculatorXYOffsetFixed2"},
		{215, "CTaskExhaustedFlee"},
		{216, "CTaskGrowlAndFlee"},
		{217, "CTaskScenarioFlee"},
		{218, "CTaskSmartFlee"},
		{219, "CTaskFlyAway"},
		{220, "CTaskWalkAway"},
		{221, "CTaskWander"},
		{222, "CTaskWanderInArea"},
		{223, "CTaskFollowLeaderInFormation"},
		{224, "CTaskGoToPointAnyMeans"},
		{225, "CTaskTurnToFaceEntityOrCoord"},
		{226, "CTaskFollowLeaderAnyMeans"},
		{228, "CTaskFlyToPoint"},
		{229, "CTaskFlyingWander"},
		{230, "CTaskGoToPointAiming"},
		{231, "CTaskGoToScenario"},
		{233, "CTaskSeekEntityAiming"},
		{234, "CTaskSlideToCoord"},
		{235, "CTaskSwimmingWander"},
		{237, "CTaskMoveTrackingEntity"},
		{238, "CTaskMoveFollowNavMesh"},
		{239, "CTaskMoveGoToPointOnRoute"},
		{240, "CTaskEscapeBlast"},
		{241, "CTaskMoveWander"},
		{242, "CTaskMoveBeInFormation"},
		{243, "CTaskMoveCrowdAroundLocation"},
		{244, "CTaskMoveCrossRoadAtTrafficLights"},
		{245, "CTaskMoveWaitForTraffic"},
		{246, "CTaskMoveGoToPointStandStillAchieveHeading"},
		{251, "CTaskMoveGetOntoMainNavMesh"},
		{252, "CTaskMoveSlideToCoord"},
		{253, "CTaskMoveGoToPointRelativeToEntityAndStandStill"},
		{254, "CTaskHelicopterStrafe"},
		{256, "CTaskGetOutOfWater"},
		{259, "CTaskMoveFollowEntityOffset"},
		{261, "CTaskFollowWaypointRecording"},
		{264, "CTaskMotionPed"},
		{265, "CTaskMotionPedLowLod"},
		{268, "CTaskHumanLocomotion"},
		{269, "CTaskMotionBasicLocomotionLowLod"},
		{270, "CTaskMotionStrafing"},
		{271, "CTaskMotionTennis"},
		{272, "CTaskMotionAiming"},
		{273, "CTaskBirdLocomotion"},
		{274, "CTaskFlightlessBirdLocomotion"},
		{278, "CTaskFishLocomotion"},
		{279, "CTaskQuadLocomotion"},
		{280, "CTaskMotionDiving"},
		{281, "CTaskMotionSwimming"},
		{282, "CTaskMotionParachuting"},
		{283, "CTaskMotionDrunk"},
		{284, "CTaskRepositionMove"},
		{285, "CTaskMotionAimingTransition"},
		{286, "CTaskThrowProjectile"},
		{287, "CTaskCover"},
		{288, "CTaskMotionInCover"},
		{289, "CTaskAimAndThrowProjectile"},
		{290, "CTaskGun"},
		{291, "CTaskAimFromGround"},
		{295, "CTaskAimGunVehicleDriveBy"},
		{296, "CTaskAimGunScripted"},
		{298, "CTaskReloadGun"},
		{299, "CTaskWeaponBlocked"},
		{300, "CTaskEnterCover"},
		{301, "CTaskExitCover"},
		{302, "CTaskAimGunFromCoverIntro"},
		{303, "CTaskAimGunFromCoverOutro"},
		{304, "CTaskAimGunBlindFire"},
		{307, "CTaskCombatClosestTargetInArea"},
		{308, "CTaskCombatAdditionalTask"},
		{309, "CTaskInCover"},
		{313, "CTaskAimSweep"},
		{319, "CTaskSharkCircle"},
		{320, "CTaskSharkAttack"},
		{321, "CTaskAgitated"},
		{322, "CTaskAgitatedAction"},
		{323, "CTaskConfront"},
		{324, "CTaskIntimidate"},
		{325, "CTaskShove"},
		{326, "CTaskShoved"},
		{328, "CTaskCrouchToggle"},
		{329, "CTaskRevive"},
		{335, "CTaskParachute"},
		{336, "CTaskParachuteObject"},
		{337, "CTaskTakeOffPedVariation"},
		{340, "CTaskCombatSeekCover"},
		{342, "CTaskCombatFlank"},
		{343, "CTaskCombat"},
		{344, "CTaskCombatMounted"},
		{345, "CTaskMoveCircle"},
		{346, "CTaskMoveCombatMounted"},
		{347, "CTaskSearch"},
		{348, "CTaskSearchOnFoot"},
		{349, "CTaskSearchInAutomobile"},
		{350, "CTaskSearchInBoat"},
		{351, "CTaskSearchInHeli"},
		{352, "CTaskThreatResponse"},
		{353, "CTaskInvestigate"},
		{354, "CTaskStandGuardFSM"},
		{355, "CTaskPatrol"},
		{356, "CTaskShootAtTarget"},
		{357, "CTaskSetAndGuardArea"},
		{358, "CTaskStandGuard"},
		{359, "CTaskSeparate"},
		{360, "CTaskStayInCover"},
		{361, "CTaskVehicleCombat"},
		{362, "CTaskVehiclePersuit"},
		{363, "CTaskVehicleChase"},
		{364, "CTaskDraggingToSafety"},
		{365, "CTaskDraggedToSafety"},
		{366, "CTaskVariedAimPose"},
		{367, "CTaskMoveWithinAttackWindow"},
		{368, "CTaskMoveWithinDefensiveArea"},
		{369, "CTaskShootOutTire"},
		{370, "CTaskShellShocked"},
		{371, "CTaskBoatChase"},
		{372, "CTaskBoatCombat"},
		{373, "CTaskBoatStrafe"},
		{374, "CTaskHeliChase"},
		{375, "CTaskHeliCombat"},
		{376, "CTaskSubmarineCombat"},
		{377, "CTaskSubmarineChase"},
		{378, "CTaskPlaneChase"},
		{379, "CTaskTargetUnreachable"},
		{380, "CTaskTargetUnreachableInInterior"},
		{381, "CTaskTargetUnreachableInExterior"},
		{382, "CTaskStealthKill"},
		{383, "CTaskWrithe"},
		{384, "CTaskAdvance"},
		{385, "CTaskCharge"},
		{386, "CTaskMoveToTacticalPoint"},
		{387, "CTaskToHurtTransit"},
		{388, "CTaskAnimatedHitByExplosion"},
		{389, "CTaskNMRelax"},
		{391, "CTaskNMPose"},
		{392, "CTaskNMBrace"},
		{393, "CTaskNMBuoyancy"},
		{394, "CTaskNMInjuredOnGround"},
		{395, "CTaskNMShot"},
		{396, "CTaskNMHighFall"},
		{397, "CTaskNMBalance"},
		{398, "CTaskNMElectrocute"},
		{399, "CTaskNMPrototype"},
		{400, "CTaskNMExplosion"},
		{401, "CTaskNMOnFire"},
		{402, "CTaskNMScriptControl"},
		{403, "CTaskNMJumpRollFromRoadVehicle"},
		{404, "CTaskNMFlinch"},
		{405, "CTaskNMSit"},
		{406, "CTaskNMFallDown"},
		{407, "CTaskBlendFromNM"},
		{408, "CTaskNMControl"},
		{409, "CTaskNMDangle"},
		{412, "CTaskNMGenericAttach"},
		{414, "CTaskNMDraggingToSafety"},
		{415, "CTaskNMThroughWindscreen"},
		{416, "CTaskNMRiverRapids"},
		{417, "CTaskNMSimple"},
		{418, "CTaskRageRagdoll"},
		{421, "CTaskJumpVault"},
		{422, "CTaskJump"},
		{423, "CTaskFall"},
		{425, "CTaskReactAimWeapon"},
		{426, "CTaskChat"},
		{427, "CTaskMobilePhone"},
		{428, "CTaskReactToDeadPed"},
		{430, "CTaskSearchForUnknownThreat"},
		{432, "CTaskBomb"},
		{433, "CTaskDetonator"},
		{435, "CTaskAnimatedAttach"},
		{441, "CTaskCutScene"},
		{442, "CTaskReactToExplosion"},
		{443, "CTaskReactToImminentExplosion"},
		{444, "CTaskDiveToGround"},
		{445, "CTaskReactAndFlee"},
		{446, "CTaskSidestep"},
		{447, "CTaskCallPolice"},
		{448, "CTaskReactInDirection"},
		{449, "CTaskReactToBuddyShot"},
		{454, "CTaskVehicleGoToAutomobileNew"},
		{455, "CTaskVehicleGoToPlane"},
		{456, "CTaskVehicleGoToHelicopter"},
		{457, "CTaskVehicleGoToSubmarine"},
		{458, "CTaskVehicleGoToBoat"},
		{459, "CTaskVehicleGoToPointAutomobile"},
		{460, "CTaskVehicleGoToPointWithAvoidanceAutomobile"},
		{461, "CTaskVehiclePursue"},
		{462, "CTaskVehicleRam"},
		{463, "CTaskVehicleSpinOut"},
		{464, "CTaskVehicleApproach"},
		{465, "CTaskVehicleThreePointTurn"},
		{466, "CTaskVehicleDeadDriver"},
		{467, "CTaskVehicleCruiseNew"},
		{468, "CTaskVehicleCruiseBoat"},
		{469, "CTaskVehicleStop"},
		{470, "CTaskVehiclePullOver"},
		{471, "CTaskVehiclePassengerExit"},
		{472, "CTaskVehicleFlee"},
		{473, "CTaskVehicleFleeAirborne"},
		{474, "CTaskVehicleFleeBoat"},
		{475, "CTaskVehicleFollowRecording"},
		{476, "CTaskVehicleFollow"},
		{477, "CTaskVehicleBlock"},
		{478, "CTaskVehicleBlockCruiseInFront"},
		{479, "CTaskVehicleBlockBrakeInFront"},
		{478, "CTaskVehicleBlockBackAndForth"},
		{481, "CTaskVehicleCrash"},
		{482, "CTaskVehicleLand"},
		{483, "CTaskVehicleLandPlane"},
		{484, "CTaskVehicleHover"},
		{485, "CTaskVehicleAttack"},
		{486, "CTaskVehicleAttackTank"},
		{487, "CTaskVehicleCircle"},
		{488, "CTaskVehiclePoliceBehaviour"},
		{489, "CTaskVehiclePoliceBehaviourHelicopter"},
		{490, "CTaskVehiclePoliceBehaviourBoat"},
		{491, "CTaskVehicleEscort"},
		{492, "CTaskVehicleHeliProtect"},
		{494, "CTaskVehiclePlayerDriveAutomobile"},
		{495, "CTaskVehiclePlayerDriveBike"},
		{496, "CTaskVehiclePlayerDriveBoat"},
		{497, "CTaskVehiclePlayerDriveSubmarine"},
		{498, "CTaskVehiclePlayerDriveSubmarineCar"},
		{499, "CTaskVehiclePlayerDriveAmphibiousAutomobile"},
		{500, "CTaskVehiclePlayerDrivePlane"},
		{501, "CTaskVehiclePlayerDriveHeli"},
		{502, "CTaskVehiclePlayerDriveAutogyro"},
		{503, "CTaskVehiclePlayerDriveDiggerArm"},
		{504, "CTaskVehiclePlayerDriveTrain"},
		{505, "CTaskVehiclePlaneChase"},
		{506, "CTaskVehicleNoDriver"},
		{507, "CTaskVehicleAnimation"},
		{508, "CTaskVehicleConvertibleRoof"},
		{509, "CTaskVehicleParkNew"},
		{510, "CTaskVehicleFollowWaypointRecording"},
		{511, "CTaskVehicleGoToNavmesh"},
		{512, "CTaskVehicleReactToCopSiren"},
		{513, "CTaskVehicleGotoLongRange"},
		{514, "CTaskVehicleWait"},
		{515, "CTaskVehicleReverse"},
		{516, "CTaskVehicleBrake"},
		{517, "CTaskVehicleHandBrake"},
		{518, "CTaskVehicleTurn"},
		{519, "CTaskVehicleGoForward"},
		{520, "CTaskVehicleSwerve"},
		{521, "CTaskVehicleFlyDirection"},
		{522, "CTaskVehicleHeadonCollision"},
		{523, "CTaskVehicleBoostUseSteeringAngle"},
		{524, "CTaskVehicleShotTire"},
		{525, "CTaskVehicleBurnout"},
		{526, "CTaskVehicleRevEngine"},
		{527, "CTaskVehicleSurfaceInSubmarine"},
		{528, "CTaskVehiclePullAlongside"},
		{529, "CTaskVehicleTransformToSubmarine"},
		{530, "CTaskAnimatedFallback"},
		{531, "None"},
	};
}

class node_id
{
public:
	constexpr node_id()
	{
		id = 0;
	}

	template <size_t N>
	constexpr node_id(const char(&pp)[N])
	{
		id = joaat_from_char_array(pp);
	}

	constexpr operator uint32_t() const
	{
		return id;
	}

	uint32_t id{};
};

class node_finder
{
public:
	static constexpr uint64_t m_sync_tree_count{ static_cast<uint64_t>(eNetObjectType::Train) + 1 };
	std::array<std::map<uint64_t, std::vector<node_id>>, m_sync_tree_count> m_sync_tree_convertion{};
	std::array<std::vector<node_id>, m_sync_tree_count> m_sync_trees{
		{
			//Automobile
			{
				{"CVehicleCreationDataNode"},
				{"CAutomobileCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDynamicEntityGameStateDataNode"},
				{"CPhysicalGameStateDataNode"},
				{"CVehicleGameStateDataNode"},

				{"CEntityScriptGameStateDataNode"},
				{"CPhysicalScriptGameStateDataNode"},
				{"CVehicleScriptGameStateDataNode"},
				{"CEntityScriptInfoDataNode"},

				{"CPhysicalAttachDataNode"},
				{"CVehicleAppearanceDataNode"},
				{"CVehicleDamageStatusDataNode"},
				{"CVehicleComponentReservationDataNode"},
				{"CVehicleHealthDataNode"},
				{"CVehicleTaskDataNode"},

				{"CSectorDataNode"},
				{"CSectorPositionDataNode"},
				{"CEntityOrientationDataNode"},
				{"CPhysicalVelocityDataNode"},
				{"CVehicleAngVelocityDataNode"},

				{"CVehicleSteeringDataNode"},
				{"CVehicleControlDataNode"},
				{"CVehicleGadgetDataNode"},

				{"CMigrationDataNode"},
				{"CPhysicalMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
				{"CVehicleProximityMigrationDataNode"},
			},
			//Bike
			{
				{"CVehicleCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDynamicEntityGameStateDataNode"},
				{"CPhysicalGameStateDataNode"},
				{"CVehicleGameStateDataNode"},
				{"CBikeGameStateDataNode"},

				{"CEntityScriptGameStateDataNode"},
				{"CPhysicalScriptGameStateDataNode"},
				{"CVehicleScriptGameStateDataNode"},
				{"CEntityScriptInfoDataNode"},

				{"CPhysicalAttachDataNode"},
				{"CVehicleAppearanceDataNode"},
				{"CVehicleDamageStatusDataNode"},
				{"CVehicleComponentReservationDataNode"},
				{"CVehicleHealthDataNode"},
				{"CVehicleTaskDataNode"},

				{"CSectorDataNode"},
				{"CSectorPositionDataNode"},
				{"CEntityOrientationDataNode"},
				{"CPhysicalVelocityDataNode"},
				{"CVehicleAngVelocityDataNode"},

				{"CVehicleSteeringDataNode"},
				{"CVehicleControlDataNode"},
				{"CVehicleGadgetDataNode"},

				{"CMigrationDataNode"},
				{"CPhysicalMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
				{"CVehicleProximityMigrationDataNode"},
			},
			//Boaat
			{
				{"CVehicleCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDynamicEntityGameStateDataNode"},
				{"CPhysicalGameStateDataNode"},
				{"CVehicleGameStateDataNode"},
				{"CBoatGameStateDataNode"},

				{"CEntityScriptGameStateDataNode"},
				{"CPhysicalScriptGameStateDataNode"},
				{"CVehicleScriptGameStateDataNode"},
				{"CEntityScriptInfoDataNode"},

				{"CPhysicalAttachDataNode"},
				{"CVehicleAppearanceDataNode"},
				{"CVehicleDamageStatusDataNode"},
				{"CVehicleComponentReservationDataNode"},
				{"CVehicleHealthDataNode"},
				{"CVehicleTaskDataNode"},

				{"CSectorDataNode"},
				{"CSectorPositionDataNode"},
				{"CEntityOrientationDataNode"},
				{"CPhysicalVelocityDataNode"},
				{"CVehicleAngVelocityDataNode"},

				{"CVehicleSteeringDataNode"},
				{"CVehicleControlDataNode"},
				{"CVehicleGadgetDataNode"},

				{"CMigrationDataNode"},
				{"CPhysicalMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
				{"CVehicleProximityMigrationDataNode"},
			},
			//Door
			{
				{"CDoorCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDoorScriptInfoDataNode"},
				{"CDoorScriptGameStateDataNode"},

				{"CDoorMovementDataNode"},

				{"CMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
			},
			//Heli
			{
				{"CVehicleCreationDataNode"},
				{"CAutomobileCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDynamicEntityGameStateDataNode"},
				{"CPhysicalGameStateDataNode"},
				{"CVehicleGameStateDataNode"},

				{"CEntityScriptGameStateDataNode"},
				{"CPhysicalScriptGameStateDataNode"},
				{"CVehicleScriptGameStateDataNode"},
				{"CEntityScriptInfoDataNode"},

				{"CPhysicalAttachDataNode"},
				{"CVehicleAppearanceDataNode"},
				{"CVehicleDamageStatusDataNode"},
				{"CVehicleComponentReservationDataNode"},
				{"CVehicleHealthDataNode"},
				{"CVehicleTaskDataNode"},
				{"CHeliHealthDataNode"},

				{"CSectorDataNode"},
				{"CSectorPositionDataNode"},
				{"CEntityOrientationDataNode"},
				{"CPhysicalVelocityDataNode"},
				{"CVehicleAngVelocityDataNode"},

				{"CVehicleSteeringDataNode"},
				{"CVehicleControlDataNode"},
				{"CVehicleGadgetDataNode"},
				{"CHeliControlDataNode"},

				{"CMigrationDataNode"},
				{"CPhysicalMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
				{"CVehicleProximityMigrationDataNode"},
			},
			//Object
			{
				{"CObjectCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDynamicEntityGameStateDataNode"},
				{"CPhysicalGameStateDataNode"},
				{"CObjectGameStateDataNode"},

				{"CEntityScriptGameStateDataNode"},
				{"CPhysicalScriptGameStateDataNode"},
				{"CObjectScriptGameStateDataNode"},
				{"CEntityScriptInfoDataNode"},

				{"CPhysicalAttachDataNode"},
				{"CPhysicalHealthDataNode"},

				{"CSectorDataNode"},
				{"CObjectSectorPosNode"},
				{"CObjectOrientationNode"},
				{"CPhysicalVelocityDataNode"},
				{"CPhysicalAngVelocityDataNode"},

				{"CMigrationDataNode"},
				{"CPhysicalMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
			},
			//Ped
			{
				{"CPedCreationDataNode"},
				{"CPedScriptCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDynamicEntityGameStateDataNode"},
				{"CPhysicalGameStateDataNode"},
				{"CPedGameStateDataNode"},
				{"CPedComponentReservationDataNode"},

				{"CEntityScriptGameStateDataNode"},
				{"CPhysicalScriptGameStateDataNode"},
				{"CPedScriptGameStateDataNode"},
				{"CEntityScriptInfoDataNode"},

				{"CPedAttachDataNode"},
				{"CPedHealthDataNode"},
				{"CPedMovementGroupDataNode"},
				{"CPedAIDataNode"},
				{"CPedAppearanceDataNode"},

				{"CPedOrientationDataNode"},
				{"CPedMovementDataNode"},

				{"CPedTaskTreeDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},

				{"CSectorDataNode"},
				{"CPedSectorPosMapNode"},
				{"CPedSectorPosNavMeshNode"},

				{"CMigrationDataNode"},
				{"CPhysicalMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
				{"CPedInventoryDataNode"},
				{"CPedTaskSequenceDataNode"},
			},
			//Pickup
			{
				{"CPickupCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDynamicEntityGameStateDataNode"},

				{"CPickupScriptGameStateNode"},
				{"CPhysicalGameStateDataNode"},
				{"CEntityScriptGameStateDataNode"},
				{"CPhysicalScriptGameStateDataNode"},
				{"CEntityScriptInfoDataNode"},
				{"CPhysicalHealthDataNode"},

				{"CPhysicalAttachDataNode"},

				{"CSectorDataNode"},
				{"CPickupSectorPosNode"},
				{"CEntityOrientationDataNode"},
				{"CPhysicalVelocityDataNode"},
				{"CPhysicalAngVelocityDataNode"},

				{"CMigrationDataNode"},
				{"CPhysicalMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
			},
			//Pickup Placement
			{
				{"CPickupPlacementCreationDataNode"},
				{"CMigrationDataNode"},
				{"CGlobalFlagsDataNode"},
				{"CPickupPlacementStateDataNode"},
			},
			//Plane
			{
				{"CVehicleCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDynamicEntityGameStateDataNode"},
				{"CPhysicalGameStateDataNode"},
				{"CVehicleGameStateDataNode"},

				{"CEntityScriptGameStateDataNode"},
				{"CPhysicalScriptGameStateDataNode"},
				{"CVehicleScriptGameStateDataNode"},
				{"CEntityScriptInfoDataNode"},

				{"CPhysicalAttachDataNode"},
				{"CVehicleAppearanceDataNode"},
				{"CVehicleDamageStatusDataNode"},
				{"CVehicleComponentReservationDataNode"},
				{"CVehicleHealthDataNode"},
				{"CVehicleTaskDataNode"},
				{"CPlaneGameStateDataNode"},

				{"CSectorDataNode"},
				{"CSectorPositionDataNode"},
				{"CEntityOrientationDataNode"},
				{"CPhysicalVelocityDataNode"},
				{"CVehicleAngVelocityDataNode"},

				{"CVehicleSteeringDataNode"},
				{"CVehicleControlDataNode"},
				{"CVehicleGadgetDataNode"},
				{"CPlaneControlDataNode"},

				{"CMigrationDataNode"},
				{"CPhysicalMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
				{"CVehicleProximityMigrationDataNode"},
			},
			//Submarine
			{
				{"CVehicleCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDynamicEntityGameStateDataNode"},
				{"CPhysicalGameStateDataNode"},
				{"CVehicleGameStateDataNode"},
				{"CSubmarineGameStateDataNode"},

				{"CEntityScriptGameStateDataNode"},
				{"CPhysicalScriptGameStateDataNode"},
				{"CVehicleScriptGameStateDataNode"},
				{"CEntityScriptInfoDataNode"},

				{"CPhysicalAttachDataNode"},
				{"CVehicleAppearanceDataNode"},
				{"CVehicleDamageStatusDataNode"},
				{"CVehicleComponentReservationDataNode"},
				{"CVehicleHealthDataNode"},
				{"CVehicleTaskDataNode"},

				{"CSectorDataNode"},
				{"CSectorPositionDataNode"},
				{"CEntityOrientationDataNode"},
				{"CPhysicalVelocityDataNode"},
				{"CVehicleAngVelocityDataNode"},

				{"CVehicleSteeringDataNode"},
				{"CVehicleControlDataNode"},
				{"CVehicleGadgetDataNode"},
				{"CSubmarineControlDataNode"},

				{"CMigrationDataNode"},
				{"CPhysicalMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
				{"CVehicleProximityMigrationDataNode"},
			},
			//Player
			{
				{"CPlayerCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDynamicEntityGameStateDataNode"},
				{"CPhysicalGameStateDataNode"},
				{"CPedGameStateDataNode"},
				{"CPedComponentReservationDataNode"},

				{"CEntityScriptGameStateDataNode"},
				{"CPlayerGameStateDataNode"},

				{"CPedAttachDataNode"},
				{"CPedHealthDataNode"},
				{"CPedMovementGroupDataNode"},
				{"CPedAIDataNode"},
				{"CPlayerAppearanceDataNode"},
				{"CPlayerPedGroupDataNode"},
				{"CPlayerAmbientModelStreamingNode"},
				{"CPlayerGamerDataNode"},
				{"CPlayerExtendedGameStateNode"},

				{"CPedOrientationDataNode"},
				{"CPedMovementDataNode"},

				{"CPedTaskTreeDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},
				{"CPedTaskSpecificDataNode"},

				{"CSectorDataNode"},
				{"CPlayerSectorPosNode"},
				{"CPlayerCameraDataNode"},
				{"CPlayerWantedAndLOSDataNode"},

				{"CMigrationDataNode"},
				{"CPhysicalMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
			},
			//Trailer
			{

			},
			//Train
			{
				{"CVehicleCreationDataNode"},

				{"CGlobalFlagsDataNode"},
				{"CDynamicEntityGameStateDataNode"},
				{"CPhysicalGameStateDataNode"},
				{"CVehicleGameStateDataNode"},
				{"CTrainGameStateDataNode"},

				{"CEntityScriptGameStateDataNode"},
				{"CPhysicalScriptGameStateDataNode"},
				{"CVehicleScriptGameStateDataNode"},
				{"CEntityScriptInfoDataNode"},

				{"CPhysicalAttachDataNode"},
				{"CVehicleAppearanceDataNode"},
				{"CVehicleDamageStatusDataNode"},
				{"CVehicleComponentReservationDataNode"},
				{"CVehicleHealthDataNode"},
				{"CVehicleTaskDataNode"},

				{"CSectorDataNode"},
				{"CSectorPositionDataNode"},
				{"CEntityOrientationDataNode"},
				{"CPhysicalVelocityDataNode"},
				{"CVehicleAngVelocityDataNode"},

				{"CVehicleSteeringDataNode"},
				{"CVehicleControlDataNode"},
				{"CVehicleGadgetDataNode"},

				{"CMigrationDataNode"},
				{"CPhysicalMigrationDataNode"},
				{"CPhysicalScriptMigrationDataNode"},
				{"CVehicleProximityMigrationDataNode"},
			},
		},
	};
};

inline static std::pair<const char*, uint32_t> packet_types[] = {
	{"CMSG_TEXT_CHAT_STATUS", 0},
	{"REASSIGN_NEGOTIATE_MSG", 1},
	{"MSG_TRANSITION_TO_GAME_NOTIFY", 2},
	{"CMSG_VOICE_STATUS", 3},
	{"MSG_RESERVE_SLOTS_ACK", 4},
	{"RL_MSG_SEARCH_REQUEST", 5},
	{"MSG_TRANSITION_TO_ACTIVITY_START", 6},
	{"MSG_SESSION_ESTABLISHED", 7},
	{"CMSG_JOIN_RESPONSE", 8},
	{"INFORM_OBJECT_IDS_MSG", 9},
	{"MSG_TEXT_MESSAGE", 10},
	{"MSG_SCRIPT_VERIFY_HOST_ACK", 11},
	{"MSG_BLACKLIST", 12},
	{"MSG_REQUEST_KICK_FROM_HOST", 13},
	{"MSG_SCRIPT_NEW_HOST", 14},
	{"NET_KEY_EXCHANGE_SESSION_OFFER", 15},
	{"REASSIGN_RESPONSE_MSG", 16},
	{"NET_ICE_SESSION_PONG", 17},
	{"SN_MSG_MIGRATE_HOST_RESPONSE", 18},
	{"RL_SESSION_DETAIL_RESPONSE", 19},
	{"MSG_TRANSITION_GAMER_INSTRUCTION", 20},
	{"NET_ICE_SESSION_PING", 21},
	{"NON_PHYSICAL_DATA_MSG", 22},
	{"MSG_SCRIPT_LEAVE", 23},
	{"PLAYER_DATA_MSG", 24},
	{"MSG_TRANSITION_LAUNCH", 25},
	{"MSG_SCRIPT_MIGRATE_HOST_FAIL_ACK", 26},
	{"MSG_TRANSITION_LAUNCH_NOTIFY", 27},
	{"MSG_SCRIPT_BOT_JOIN", 28},
	{"RL_MSG_QOS_PROBE_REQUEST", 29},
	{"MSG_PARTY_ENTER_GAME", 30},
	{"SN_MSG_SET_INVITABLE_CMD", 31},
	{"CMSG_PACKED_EVENT_RELIABLES_MSGS", 32},
	{"NET_MESSAGE", 33},
	{"RL_SESSION_DETAIL_REQUEST", 34},
	{"SN_MSG_SESSION_MEMBER_IDS", 35},
	{"CMSG_TEXT_MESSAGE", 36},
	{"MSG_SPLIT_UPDATE_ACK", 37},
	{"REASSIGN_CONFIRM_MSG", 38},
	{"NET_LAG_PING_MSG", 39},
	{"NET_ICE_SESSION_DEBUG_INFO", 40},
	{"REQUEST_OBJECT_IDS_MSG", 41},
	{"SN_MSG_JOIN_RESPONSE", 42},
	{"MSG_SCRIPT_BOT_LEAVE", 43},
	{"RL_MSG_QOS_PROBE_RESPONSE", 44},
	{"SN_MSG_START_MATCH_CMD", 45},
	{"CROAMING_REQUEST_BUBBLE_MSG", 46},
	{"MSG_CXN_REQUEST_REMOTE_TIMEOUT", 47},
	{"PACKED_RELIABLES_MSG", 48},
	{"MSG_SCRIPT_BOT_HANDSHAKE_ACK", 49},
	{"CROAMING_INITIAL_BUBBLE_MSG", 50},
	{"MSG_SCRIPT_MIGRATE_HOST", 51},
	{"MSG_KICK_PLAYER", 52},
	{"SN_MSG_NOT_MIGRATING", 53},
	{"MSG_TRANSITION_TO_ACTIVITY_FINISH", 54},
	{"MSG_TRANSITION_PARAMETER_STRING", 55},
	{"NET_TIME_SYNC_MSG", 56},
	{"MSG_RESERVE_SLOTS", 57},
	{"MSG_PLAYER_CARD_SYNC", 58},
	{"PACKED_CLONE_SYNC_ACKS_MSG", 59},
	{"MSG_TRANSITION_PARAMETERS", 60},
	{"MSG_PARTY_LEAVE_GAME", 61},
	{"MSG_SCRIPT_VERIFY_HOST", 62},
	{"CROAMING_JOIN_BUBBLE_ACK_MSG", 63},
	{"MSG_SCRIPT_LEAVE_ACK", 64},
	{"SN_MSG_JOIN_REQUEST", 65},
	{"MSG_REQUEST_TRANSITION_PARAMETERS", 66},
	{"MSG_SCRIPT_JOIN_ACK", 67},
	{"NET_KEY_EXCHANGE_SESSION_ANSWER", 68},
	{"NET_ICE_SESSION_PORT_OPENER", 69},
	{"MSG_RADIO_STATION_SYNC", 70},
	{"MSG_RADIO_STATION_SYNC_REQUEST", 71},
	{"SN_MSG_CONFIG_REQUEST", 72},
	{"MSG_CXN_RELAY_ADDR_CHANGED", 73},
	{"NET_ICE_SESSION_ANSWER_OLD", 74},
	{"MSG_SCRIPT_BOT_HANDSHAKE", 75},
	{"CROAMING_JOIN_BUBBLE_MSG", 76},
	{"MSG_SCRIPT_JOIN_HOST_ACK", 77},
	{"CLONE_SYNC_MSG", 78},
	{"CMSG_PACKED_EVENTS", 79},
	{"MSG_TRANSITION_TO_GAME_START", 80},
	{"MSG_CHECK_QUEUED_JOIN_REQUEST", 81},
	{"MSG_SESSION_ESTABLISHED_REQUEST", 82},
	{"SN_MSG_REMOVE_GAMERS_FROM_SESSION_CMD", 83},
	{"SN_MSG_REQUEST_GAMER_INFO", 84},
	{"NET_COMPLAINT_MSG", 85},
	{"NET_ICE_SESSION_OFFER_OLD", 86},
	{"MSG_SCRIPT_HANDSHAKE", 87},
	{"SN_MSG_HOST_LEFT_WHILST_JOINING_CMD", 88},
	{"MSG_CHECK_QUEUED_JOIN_REQUEST_REPLY", 89},
	{"SN_MSG_CHANGE_SESSION_ATTRIBUTES_CMD", 90},
	{"MSG_SCRIPT_HANDSHAKE_ACK", 91},
	{"MSG_SCRIPT_JOIN", 92},
	{"MSG_UPDATE_ACK", 93},
	{"MSG_CHECK_QUEUED_JOIN_REQUEST_INVITE_REPLY", 94},
	{"SN_MSG_CONFIG_RESPONSE", 95},
	{"MSG_UPDATE", 96},
	{"CMSG_PLAYER_IS_TYPING", 97},
	{"SN_MSG_SESSION_ACCEPT_CHAT", 98},
	{"MSG_SCRIPT_BOT_JOIN_ACK", 99},
	{"SN_MSG_ADD_GAMER_TO_SESSION_CMD", 100},
	{"ACTIVATE_NETWORK_BOT_MSG", 101},
	{"SN_MSG_MIGRATE_HOST_REQUEST", 102},
	{"MSG_SCRIPT_HOST_REQUEST", 103},
	{"CMSG_JOIN_REQUEST", 104},
	{"SN_MSG_BASE", 105},
	{"MSG_PLAYER_CARD_REQUEST", 106},
	{"RL_MSG_SEARCH_RESPONSE", 107},
	{"MSG_DEBUG_TIME_SCALE", 108},
	{"MSG_DEBUG_TIME_PAUSE", 109},
	{"MSG_DEBUG_NO_TIMEOUTS", 110},
	{"MSG_DEBUG_ADD_FAIL_MARK", 111},
	{"MSG_SYNC_DR_DISPLAY", 112},
	{"SN_MSG_SESSION_INFO", 113},
	{"SN_MSG_SESSION_INFO_RESPONSE", 114},
	{"SN_MSG_SESSION_JOIN_REQUEST", 115},
	{"SN_MSG_SESSION_JOIN_REQUEST_RESPONSE", 116},
	{"CMSG_VOICE_CHAT_REQUEST", 117},
	{"CMSG_VOICE_CHAT_REPLY", 118},
	{"CMSG_VOICE_CHAT_END", 119},
	{"VOICE_CHAT_USER_MSG", 120},
	{"SESSION_INFO_MSG", 121},
	{"REGISTER_COMPLETE_MSG", 122},
	{"START_COMMAND_MSG", 123},
	{"QA_NR_FOO_MSG", 124},
	{"QA_NR_BAR_MSG", 125},
	{"MSG_DEBUG_STALL", 126},
	{"NET_ICE_SESSION_OFFER", 127},
	{"NET_ICE_SESSION_ANSWER", 128},
	{"MSG_LOST_HOST_CONNECTION", 129},
	{"CROAMING_BUBBLE_REQUIRED_CHECK_MSG", 130},
	{"CROAMING_BUBBLE_REQUIRED_RESPONSE_MSG", 131},
	{"NET_ROUTE_REQUEST_MSG", 132},
	{"NET_ROUTE_REPLY_MSG", 133},
	{"NET_ROUTE_ERR_MSG", 134},
	{"NET_ROUTE_CHANGE_REQUEST_MSG", 135},
	{"NET_ROUTE_CHANGE_REPLY_MSG", 136},
	{"NET_ICE_SESSION_RELAY_ROUTE_CHECK", 137}
};

inline constexpr std::pair<const char*, rage::joaat_t> g_ped_models[] = {
	{"Juggernaut", "u_m_y_juggernaut_01"_joaat},
	{"Johnny", "ig_johnnyklebitz"_joaat},
	{"Movspace", "s_m_m_movspace_01"_joaat},
	{"Imporage", "u_m_y_imporage"_joaat},
	{"Rs Ranger", "u_m_y_rsranger_01"_joaat},
	{"Justin", "u_m_y_justin"_joaat},
	{"Mani", "u_m_y_mani"_joaat},
	{"Agatha", "CSB_Agatha"_joaat},
	{"Agatha 2", "IG_Agatha"_joaat},
	{"Avery", "CSB_Avery"_joaat},
	{"Avery 2", "IG_Avery"_joaat},
	{"Brucie", "CSB_Brucie2"_joaat},
	{"Brucie 2", "IG_Brucie2"_joaat},
	{"TaoCheng", "IG_TaoCheng2"_joaat},
	{"TaoCheng 2", "CS_TaoCheng2"_joaat},
	{"TaosTranslator", "IG_TaosTranslator2"_joaat},
	{"TaosTranslator 2", "CS_TaosTranslator2"_joaat},
	{"Thornton", "CSB_Thornton"_joaat},
	{"Thornton 2", "IG_Thornton"_joaat},
	{"TomCasino", "CSB_TomCasino"_joaat},
	{"TomCasino 2", "IG_TomCasino"_joaat},
	{"Vincent", "CSB_Vincent"_joaat},
	{"Vincent 2", "IG_Vincent"_joaat},
	{"GenCasPat", "A_F_Y_GenCasPat_01"_joaat},
	{"GenCasPat 2", "A_F_Y_SmartCasPat_01"_joaat},
	{"MLCrisis", "A_M_M_MLCrisis_01"_joaat},
	{"GenCasPat 3", "A_M_Y_GenCasPat_01"_joaat},
	{"SmartCasPat", "A_M_Y_SmartCasPat_01"_joaat},
	{"CasRN", "G_M_M_CasRN_01"_joaat},
	{"WestSec", "S_M_Y_WestSec_01"_joaat},
	{"Casino_01 F", "S_F_Y_Casino_01"_joaat},
	{"Casino_01 M", "S_M_Y_Casino_01"_joaat},
	{"Carol", "U_F_O_Carol"_joaat},
	{"Eileen", "U_F_O_Eileen"_joaat},
	{"CasinoCash_01", "U_F_M_CasinoCash_01"_joaat},
	{"CasinoShop_01", "U_F_M_CasinoShop_01"_joaat},
	{"Debbie", "U_F_M_Debbie_01"_joaat},
	{"Beth", "U_F_Y_Beth"_joaat},
	{"Lauren", "U_F_Y_Lauren"_joaat},
	{"Taylor", "U_F_Y_Taylor"_joaat},
	{"Blane", "U_M_M_Blane"_joaat},
	{"Curtis", "U_M_M_Curtis"_joaat},
	{"Vince", "U_M_M_Vince"_joaat},
	{"Dean", "U_M_O_Dean"_joaat},
	{"Caleb", "U_M_Y_Caleb"_joaat},
	{"CroupThief_01", "U_M_Y_CroupThief_01"_joaat},
	{"Gabriel", "U_M_Y_Gabriel"_joaat},
	{"Ushi", "U_M_Y_Ushi"_joaat},
	{"Michael", "player_zero"_joaat},
	{"Franklin", "player_one"_joaat},
	{"Trevor", "player_two"_joaat},
	{"Boar", "a_c_boar"_joaat},
	{"Chimp", "a_c_chimp"_joaat},
	{"Cow", "a_c_cow"_joaat},
	{"Coyote", "a_c_coyote"_joaat},
	{"Deer", "a_c_deer"_joaat},
	{"Fish", "a_c_fish"_joaat},
	{"Hen", "a_c_hen"_joaat},
	{"Cat", "a_c_cat_01"_joaat},
	{"Hawk", "a_c_chickenhawk"_joaat},
	{"Cormorant", "a_c_cormorant"_joaat},
	{"Crow", "a_c_crow"_joaat},
	{"Dolphin", "a_c_dolphin"_joaat},
	{"Humpback", "a_c_humpback"_joaat},
	{"Whale", "a_c_killerwhale"_joaat},
	{"Pigeon", "a_c_pigeon"_joaat},
	{"Seagull", "a_c_seagull"_joaat},
	{"Sharkhammer", "a_c_sharkhammer"_joaat},
	{"Pig", "a_c_pig"_joaat},
	{"Rat", "a_c_rat"_joaat},
	{"Rhesus", "a_c_rhesus"_joaat},
	{"Chop", "a_c_chop"_joaat},
	{"Husky", "a_c_husky"_joaat},
	{"Mtlion", "a_c_mtlion"_joaat},
	{"Retriever", "a_c_retriever"_joaat},
	{"Sharktiger", "a_c_sharktiger"_joaat},
	{"Shepherd", "a_c_shepherd"_joaat},
	{"Alien", "s_m_m_movalien_01"_joaat},
	{"Beach", "a_f_m_beach_01"_joaat},
	{"Bevhills", "a_f_m_bevhills_01"_joaat},
	{"Bevhills", "a_f_m_bevhills_02"_joaat},
	{"Bodybuild", "a_f_m_bodybuild_01"_joaat},
	{"Business", "a_f_m_business_02"_joaat},
	{"Downtown", "a_f_m_downtown_01"_joaat},
	{"Eastsa", "a_f_m_eastsa_01"_joaat},
	{"Eastsa", "a_f_m_eastsa_02"_joaat},
	{"Fatbla", "a_f_m_fatbla_01"_joaat},
	{"Fatcult", "a_f_m_fatcult_01"_joaat},
	{"Fatwhite", "a_f_m_fatwhite_01"_joaat},
	{"Ktown", "a_f_m_ktown_01"_joaat},
	{"Ktown", "a_f_m_ktown_02"_joaat},
	{"Prolhost", "a_f_m_prolhost_01"_joaat},
	{"Salton", "a_f_m_salton_01"_joaat},
	{"Skidrow", "a_f_m_skidrow_01"_joaat},
	{"Soucentmc", "a_f_m_soucentmc_01"_joaat},
	{"Soucent", "a_f_m_soucent_01"_joaat},
	{"Soucent", "a_f_m_soucent_02"_joaat},
	{"Tourist", "a_f_m_tourist_01"_joaat},
	{"Trampbeac", "a_f_m_trampbeac_01"_joaat},
	{"Tramp", "a_f_m_tramp_01"_joaat},
	{"Genstreet", "a_f_o_genstreet_01"_joaat},
	{"Indian", "a_f_o_indian_01"_joaat},
	{"Ktown", "a_f_o_ktown_01"_joaat},
	{"Salton", "a_f_o_salton_01"_joaat},
	{"Soucent", "a_f_o_soucent_01"_joaat},
	{"Soucent", "a_f_o_soucent_02"_joaat},
	{"Beach", "a_f_y_beach_01"_joaat},
	{"Bevhills", "a_f_y_bevhills_01"_joaat},
	{"Bevhills", "a_f_y_bevhills_02"_joaat},
	{"Bevhills", "a_f_y_bevhills_03"_joaat},
	{"Bevhills", "a_f_y_bevhills_04"_joaat},
	{"Business", "a_f_y_business_01"_joaat},
	{"Business", "a_f_y_business_02"_joaat},
	{"Business", "a_f_y_business_03"_joaat},
	{"Business", "a_f_y_business_04"_joaat},
	{"Eastsa", "a_f_y_eastsa_01"_joaat},
	{"Eastsa", "a_f_y_eastsa_02"_joaat},
	{"Eastsa", "a_f_y_eastsa_03"_joaat},
	{"Epsilon", "a_f_y_epsilon_01"_joaat},
	{"Fitness", "a_f_y_fitness_01"_joaat},
	{"Fitness", "a_f_y_fitness_02"_joaat},
	{"Genhot", "a_f_y_genhot_01"_joaat},
	{"Golfer", "a_f_y_golfer_01"_joaat},
	{"Hiker", "a_f_y_hiker_01"_joaat},
	{"Hippie", "a_f_y_hippie_01"_joaat},
	{"Hipster", "a_f_y_hipster_01"_joaat},
	{"Hipster", "a_f_y_hipster_02"_joaat},
	{"Hipster", "a_f_y_hipster_03"_joaat},
	{"Hipster", "a_f_y_hipster_04"_joaat},
	{"Indian", "a_f_y_indian_01"_joaat},
	{"Juggalo", "a_f_y_juggalo_01"_joaat},
	{"Runner", "a_f_y_runner_01"_joaat},
	{"Rurmeth", "a_f_y_rurmeth_01"_joaat},
	{"Scdressy", "a_f_y_scdressy_01"_joaat},
	{"Skater", "a_f_y_skater_01"_joaat},
	{"Soucent", "a_f_y_soucent_01"_joaat},
	{"Soucent", "a_f_y_soucent_02"_joaat},
	{"Soucent", "a_f_y_soucent_03"_joaat},
	{"Tennis", "a_f_y_tennis_01"_joaat},
	{"Topless", "a_f_y_topless_01"_joaat},
	{"Tourist", "a_f_y_tourist_01"_joaat},
	{"Tourist", "a_f_y_tourist_02"_joaat},
	{"Vinewood", "a_f_y_vinewood_01"_joaat},
	{"Vinewood", "a_f_y_vinewood_02"_joaat},
	{"Vinewood", "a_f_y_vinewood_03"_joaat},
	{"Vinewood", "a_f_y_vinewood_04"_joaat},
	{"Yoga", "a_f_y_yoga_01"_joaat},
	{"Acult", "a_m_m_acult_01"_joaat},
	{"Afriamer", "a_m_m_afriamer_01"_joaat},
	{"Beach", "a_m_m_beach_01"_joaat},
	{"Beach", "a_m_m_beach_02"_joaat},
	{"Bevhills", "a_m_m_bevhills_01"_joaat},
	{"Bevhills", "a_m_m_bevhills_02"_joaat},
	{"Business", "a_m_m_business_01"_joaat},
	{"Eastsa", "a_m_m_eastsa_01"_joaat},
	{"Eastsa", "a_m_m_eastsa_02"_joaat},
	{"Farmer", "a_m_m_farmer_01"_joaat},
	{"Fatlatin", "a_m_m_fatlatin_01"_joaat},
	{"Genfat", "a_m_m_genfat_01"_joaat},
	{"Genfat", "a_m_m_genfat_02"_joaat},
	{"Golfer", "a_m_m_golfer_01"_joaat},
	{"Hasjew", "a_m_m_hasjew_01"_joaat},
	{"Hillbilly", "a_m_m_hillbilly_01"_joaat},
	{"Hillbilly", "a_m_m_hillbilly_02"_joaat},
	{"Indian", "a_m_m_indian_01"_joaat},
	{"Ktown", "a_m_m_ktown_01"_joaat},
	{"Malibu", "a_m_m_malibu_01"_joaat},
	{"Mexcntry", "a_m_m_mexcntry_01"_joaat},
	{"Mexlabor", "a_m_m_mexlabor_01"_joaat},
	{"Og_boss", "a_m_m_og_boss_01"_joaat},
	{"Paparazzi", "a_m_m_paparazzi_01"_joaat},
	{"Polynesian", "a_m_m_polynesian_01"_joaat},
	{"Prolhost", "a_m_m_prolhost_01"_joaat},
	{"Rurmeth", "a_m_m_rurmeth_01"_joaat},
	{"Salton", "a_m_m_salton_01"_joaat},
	{"Salton", "a_m_m_salton_02"_joaat},
	{"Salton", "a_m_m_salton_03"_joaat},
	{"Salton", "a_m_m_salton_04"_joaat},
	{"Skater", "a_m_m_skater_01"_joaat},
	{"Skidrow", "a_m_m_skidrow_01"_joaat},
	{"Socenlat", "a_m_m_socenlat_01"_joaat},
	{"Soucent", "a_m_m_soucent_01"_joaat},
	{"Soucent", "a_m_m_soucent_02"_joaat},
	{"Soucent", "a_m_m_soucent_03"_joaat},
	{"Soucent", "a_m_m_soucent_04"_joaat},
	{"Stlat", "a_m_m_stlat_02"_joaat},
	{"Tennis", "a_m_m_tennis_01"_joaat},
	{"Tourist", "a_m_m_tourist_01"_joaat},
	{"Trampbeac", "a_m_m_trampbeac_01"_joaat},
	{"Tramp", "a_m_m_tramp_01"_joaat},
	{"Tranvest", "a_m_m_tranvest_01"_joaat},
	{"Tranvest", "a_m_m_tranvest_02"_joaat},
	{"Acult", "a_m_o_acult_01"_joaat},
	{"Acult", "a_m_o_acult_02"_joaat},
	{"Beach", "a_m_o_beach_01"_joaat},
	{"Genstreet", "a_m_o_genstreet_01"_joaat},
	{"Ktown", "a_m_o_ktown_01"_joaat},
	{"Salton", "a_m_o_salton_01"_joaat},
	{"Soucent", "a_m_o_soucent_01"_joaat},
	{"Soucent", "a_m_o_soucent_02"_joaat},
	{"Soucent", "a_m_o_soucent_03"_joaat},
	{"Tramp", "a_m_o_tramp_01"_joaat},
	{"Acult", "a_m_y_acult_01"_joaat},
	{"Acult", "a_m_y_acult_02"_joaat},
	{"Beachvesp", "a_m_y_beachvesp_01"_joaat},
	{"Beachvesp", "a_m_y_beachvesp_02"_joaat},
	{"Beach", "a_m_y_beach_01"_joaat},
	{"Beach", "a_m_y_beach_02"_joaat},
	{"Beach", "a_m_y_beach_03"_joaat},
	{"Bevhills", "a_m_y_bevhills_01"_joaat},
	{"Bevhills", "a_m_y_bevhills_02"_joaat},
	{"Breakdance", "a_m_y_breakdance_01"_joaat},
	{"Busicas", "a_m_y_busicas_01"_joaat},
	{"Business", "a_m_y_business_01"_joaat},
	{"Business", "a_m_y_business_02"_joaat},
	{"Business", "a_m_y_business_03"_joaat},
	{"Cyclist", "a_m_y_cyclist_01"_joaat},
	{"Dhill", "a_m_y_dhill_01"_joaat},
	{"Downtown", "a_m_y_downtown_01"_joaat},
	{"Eastsa", "a_m_y_eastsa_01"_joaat},
	{"Eastsa", "a_m_y_eastsa_02"_joaat},
	{"Epsilon", "a_m_y_epsilon_01"_joaat},
	{"Epsilon", "a_m_y_epsilon_02"_joaat},
	{"Gay", "a_m_y_gay_01"_joaat},
	{"Gay", "a_m_y_gay_02"_joaat},
	{"Genstreet", "a_m_y_genstreet_01"_joaat},
	{"Genstreet", "a_m_y_genstreet_02"_joaat},
	{"Golfer", "a_m_y_golfer_01"_joaat},
	{"Hasjew", "a_m_y_hasjew_01"_joaat},
	{"Hiker", "a_m_y_hiker_01"_joaat},
	{"Hippy", "a_m_y_hippy_01"_joaat},
	{"Hipster", "a_m_y_hipster_01"_joaat},
	{"Hipster", "a_m_y_hipster_02"_joaat},
	{"Hipster", "a_m_y_hipster_03"_joaat},
	{"Indian", "a_m_y_indian_01"_joaat},
	{"Jetski", "a_m_y_jetski_01"_joaat},
	{"Juggalo", "a_m_y_juggalo_01"_joaat},
	{"Ktown", "a_m_y_ktown_01"_joaat},
	{"Ktown", "a_m_y_ktown_02"_joaat},
	{"Latino", "a_m_y_latino_01"_joaat},
	{"Methhead", "a_m_y_methhead_01"_joaat},
	{"Mexthug", "a_m_y_mexthug_01"_joaat},
	{"Motox", "a_m_y_motox_01"_joaat},
	{"Motox", "a_m_y_motox_02"_joaat},
	{"Musclbeac", "a_m_y_musclbeac_01"_joaat},
	{"Musclbeac", "a_m_y_musclbeac_02"_joaat},
	{"Polynesian", "a_m_y_polynesian_01"_joaat},
	{"Roadcyc", "a_m_y_roadcyc_01"_joaat},
	{"Runner", "a_m_y_runner_01"_joaat},
	{"Runner", "a_m_y_runner_02"_joaat},
	{"Salton", "a_m_y_salton_01"_joaat},
	{"Skater", "a_m_y_skater_01"_joaat},
	{"Skater", "a_m_y_skater_02"_joaat},
	{"Soucent", "a_m_y_soucent_01"_joaat},
	{"Soucent", "a_m_y_soucent_02"_joaat},
	{"Soucent", "a_m_y_soucent_03"_joaat},
	{"Soucent", "a_m_y_soucent_04"_joaat},
	{"Stbla", "a_m_y_stbla_01"_joaat},
	{"Stbla", "a_m_y_stbla_02"_joaat},
	{"Stlat", "a_m_y_stlat_01"_joaat},
	{"Stwhi", "a_m_y_stwhi_01"_joaat},
	{"Stwhi", "a_m_y_stwhi_02"_joaat},
	{"Sunbathe", "a_m_y_sunbathe_01"_joaat},
	{"Surfer", "a_m_y_surfer_01"_joaat},
	{"Vindouche", "a_m_y_vindouche_01"_joaat},
	{"Vinewood", "a_m_y_vinewood_01"_joaat},
	{"Vinewood", "a_m_y_vinewood_02"_joaat},
	{"Vinewood", "a_m_y_vinewood_03"_joaat},
	{"Vinewood", "a_m_y_vinewood_04"_joaat},
	{"Yoga", "a_m_y_yoga_01"_joaat},
	{"Proldriver", "u_m_y_proldriver_01"_joaat},
	{"Sbike", "u_m_y_sbike"_joaat},
	{"Staggrm", "u_m_y_staggrm_01"_joaat},
	{"Tattoo", "u_m_y_tattoo_01"_joaat},
	{"Abigail", "csb_abigail"_joaat},
	{"Anita", "csb_anita"_joaat},
	{"Anton", "csb_anton"_joaat},
	{"Ballasog", "csb_ballasog"_joaat},
	{"Bride", "csb_bride"_joaat},
	{"Burgerdrug", "csb_burgerdrug"_joaat},
	{"Car3guy1", "csb_car3guy1"_joaat},
	{"Car3guy2", "csb_car3guy2"_joaat},
	{"Chef", "csb_chef"_joaat},
	{"Chin_goon", "csb_chin_goon"_joaat},
	{"Cletus", "csb_cletus"_joaat},
	{"Cop", "csb_cop"_joaat},
	{"Customer", "csb_customer"_joaat},
	{"Denise_friend", "csb_denise_friend"_joaat},
	{"Fos_rep", "csb_fos_rep"_joaat},
	{"G", "csb_g"_joaat},
	{"Groom", "csb_groom"_joaat},
	{"Dlr", "csb_grove_str_dlr"_joaat},
	{"Hao", "csb_hao"_joaat},
	{"Hugh", "csb_hugh"_joaat},
	{"Imran", "csb_imran"_joaat},
	{"Janitor", "csb_janitor"_joaat},
	{"Maude", "csb_maude"_joaat},
	{"Mweather", "csb_mweather"_joaat},
	{"Ortega", "csb_ortega"_joaat},
	{"Oscar", "csb_oscar"_joaat},
	{"Porndudes", "csb_porndudes"_joaat},
	{"Porndudes_p", "csb_porndudes_p"_joaat},
	{"Prologuedriver", "csb_prologuedriver"_joaat},
	{"Prolsec", "csb_prolsec"_joaat},
	{"Gang", "csb_ramp_gang"_joaat},
	{"Hic", "csb_ramp_hic"_joaat},
	{"Hipster", "csb_ramp_hipster"_joaat},
	{"Marine", "csb_ramp_marine"_joaat},
	{"Mex", "csb_ramp_mex"_joaat},
	{"Reporter", "csb_reporter"_joaat},
	{"Roccopelosi", "csb_roccopelosi"_joaat},
	{"Screen_writer", "csb_screen_writer"_joaat},
	{"Stripper", "csb_stripper_01"_joaat},
	{"Stripper", "csb_stripper_02"_joaat},
	{"Tonya", "csb_tonya"_joaat},
	{"Trafficwarden", "csb_trafficwarden"_joaat},
	{"Amandatownley", "cs_amandatownley"_joaat},
	{"Andreas", "cs_andreas"_joaat},
	{"Ashley", "cs_ashley"_joaat},
	{"Bankman", "cs_bankman"_joaat},
	{"Barry", "cs_barry"_joaat},
	{"Barry_p", "cs_barry_p"_joaat},
	{"Beverly", "cs_beverly"_joaat},
	{"Beverly_p", "cs_beverly_p"_joaat},
	{"Brad", "cs_brad"_joaat},
	{"Bradcadaver", "cs_bradcadaver"_joaat},
	{"Carbuyer", "cs_carbuyer"_joaat},
	{"Casey", "cs_casey"_joaat},
	{"Chengsr", "cs_chengsr"_joaat},
	{"Chrisformage", "cs_chrisformage"_joaat},
	{"Clay", "cs_clay"_joaat},
	{"Dale", "cs_dale"_joaat},
	{"Davenorton", "cs_davenorton"_joaat},
	{"Debra", "cs_debra"_joaat},
	{"Denise", "cs_denise"_joaat},
	{"Devin", "cs_devin"_joaat},
	{"Dom", "cs_dom"_joaat},
	{"Dreyfuss", "cs_dreyfuss"_joaat},
	{"Drfriedlander", "cs_drfriedlander"_joaat},
	{"Fabien", "cs_fabien"_joaat},
	{"Fbisuit", "cs_fbisuit_01"_joaat},
	{"Floyd", "cs_floyd"_joaat},
	{"Guadalope", "cs_guadalope"_joaat},
	{"Gurk", "cs_gurk"_joaat},
	{"Hunter", "cs_hunter"_joaat},
	{"Janet", "cs_janet"_joaat},
	{"Jewelass", "cs_jewelass"_joaat},
	{"Jimmyboston", "cs_jimmyboston"_joaat},
	{"Jimmydisanto", "cs_jimmydisanto"_joaat},
	{"Joeminuteman", "cs_joeminuteman"_joaat},
	{"Johnnyklebitz", "cs_johnnyklebitz"_joaat},
	{"Josef", "cs_josef"_joaat},
	{"Josh", "cs_josh"_joaat},
	{"Lamardavis", "cs_lamardavis"_joaat},
	{"Lazlow", "cs_lazlow"_joaat},
	{"Lestercrest", "cs_lestercrest"_joaat},
	{"Lifeinvad", "cs_lifeinvad_01"_joaat},
	{"Magenta", "cs_magenta"_joaat},
	{"Manuel", "cs_manuel"_joaat},
	{"Marnie", "cs_marnie"_joaat},
	{"Martinmadrazo", "cs_martinmadrazo"_joaat},
	{"Maryann", "cs_maryann"_joaat},
	{"Michelle", "cs_michelle"_joaat},
	{"Milton", "cs_milton"_joaat},
	{"Molly", "cs_molly"_joaat},
	{"Movpremf", "cs_movpremf_01"_joaat},
	{"Movpremmale", "cs_movpremmale"_joaat},
	{"Mrk", "cs_mrk"_joaat},
	{"Mrsphillips", "cs_mrsphillips"_joaat},
	{"Mrs_thornhill", "cs_mrs_thornhill"_joaat},
	{"Natalia", "cs_natalia"_joaat},
	{"Nervousron", "cs_nervousron"_joaat},
	{"Nigel", "cs_nigel"_joaat},
	{"Old_man1a", "cs_old_man1a"_joaat},
	{"Old_man2", "cs_old_man2"_joaat},
	{"Omega", "cs_omega"_joaat},
	{"Orleans", "cs_orleans"_joaat},
	{"Paper", "cs_paper"_joaat},
	{"Paper_p", "cs_paper_p"_joaat},
	{"Patricia", "cs_patricia"_joaat},
	{"Priest", "cs_priest"_joaat},
	{"Prolsec", "cs_prolsec_02"_joaat},
	{"Russiandrunk", "cs_russiandrunk"_joaat},
	{"Siemonyetarian", "cs_siemonyetarian"_joaat},
	{"Solomon", "cs_solomon"_joaat},
	{"Stevehains", "cs_stevehains"_joaat},
	{"Stretch", "cs_stretch"_joaat},
	{"Tanisha", "cs_tanisha"_joaat},
	{"Taocheng", "cs_taocheng"_joaat},
	{"Taostranslator", "cs_taostranslator"_joaat},
	{"Tenniscoach", "cs_tenniscoach"_joaat},
	{"Terry", "cs_terry"_joaat},
	{"Tom", "cs_tom"_joaat},
	{"Tomepsilon", "cs_tomepsilon"_joaat},
	{"Tracydisanto", "cs_tracydisanto"_joaat},
	{"Wade", "cs_wade"_joaat},
	{"Zimbor", "cs_zimbor"_joaat},
	{"Ballas", "g_f_y_ballas_01"_joaat},
	{"Families", "g_f_y_families_01"_joaat},
	{"Lost", "g_f_y_lost_01"_joaat},
	{"Vagos", "g_f_y_vagos_01"_joaat},
	{"Armboss", "g_m_m_armboss_01"_joaat},
	{"Armgoon", "g_m_m_armgoon_01"_joaat},
	{"Armlieut", "g_m_m_armlieut_01"_joaat},
	{"Chemwork", "g_m_m_chemwork_01"_joaat},
	{"Chemwork_p", "g_m_m_chemwork_01_p"_joaat},
	{"Chiboss", "g_m_m_chiboss_01"_joaat},
	{"Chiboss_p", "g_m_m_chiboss_01_p"_joaat},
	{"Chicold", "g_m_m_chicold_01"_joaat},
	{"Chicold_p", "g_m_m_chicold_01_p"_joaat},
	{"Chigoon", "g_m_m_chigoon_01"_joaat},
	{"Chigoon_p", "g_m_m_chigoon_01_p"_joaat},
	{"Chigoon", "g_m_m_chigoon_02"_joaat},
	{"Korboss", "g_m_m_korboss_01"_joaat},
	{"Mexboss", "g_m_m_mexboss_01"_joaat},
	{"Mexboss", "g_m_m_mexboss_02"_joaat},
	{"Armgoon", "g_m_y_armgoon_02"_joaat},
	{"Azteca", "g_m_y_azteca_01"_joaat},
	{"Ballaeast", "g_m_y_ballaeast_01"_joaat},
	{"Ballaorig", "g_m_y_ballaorig_01"_joaat},
	{"Ballasout", "g_m_y_ballasout_01"_joaat},
	{"Famca", "g_m_y_famca_01"_joaat},
	{"Famdnf", "g_m_y_famdnf_01"_joaat},
	{"Famfor", "g_m_y_famfor_01"_joaat},
	{"Korean", "g_m_y_korean_01"_joaat},
	{"Korean", "g_m_y_korean_02"_joaat},
	{"Korlieut", "g_m_y_korlieut_01"_joaat},
	{"Lost", "g_m_y_lost_01"_joaat},
	{"Lost", "g_m_y_lost_02"_joaat},
	{"Lost", "g_m_y_lost_03"_joaat},
	{"Mexgang", "g_m_y_mexgang_01"_joaat},
	{"Mexgoon", "g_m_y_mexgoon_01"_joaat},
	{"Mexgoon", "g_m_y_mexgoon_02"_joaat},
	{"Mexgoon", "g_m_y_mexgoon_03"_joaat},
	{"Mexgoon_p", "g_m_y_mexgoon_03_p"_joaat},
	{"Pologoon", "g_m_y_pologoon_01"_joaat},
	{"Pologoon_p", "g_m_y_pologoon_01_p"_joaat},
	{"Pologoon", "g_m_y_pologoon_02"_joaat},
	{"Pologoon_p", "g_m_y_pologoon_02_p"_joaat},
	{"Salvaboss", "g_m_y_salvaboss_01"_joaat},
	{"Salvagoon", "g_m_y_salvagoon_01"_joaat},
	{"Salvagoon", "g_m_y_salvagoon_02"_joaat},
	{"Salvagoon", "g_m_y_salvagoon_03"_joaat},
	{"Salvagoon_p", "g_m_y_salvagoon_03_p"_joaat},
	{"Strpunk", "g_m_y_strpunk_01"_joaat},
	{"Strpunk", "g_m_y_strpunk_02"_joaat},
	{"Hc_driver", "hc_driver"_joaat},
	{"Hc_gunman", "hc_gunman"_joaat},
	{"Hc_hacker", "hc_hacker"_joaat},
	{"Abigail", "ig_abigail"_joaat},
	{"Amandatownley", "ig_amandatownley"_joaat},
	{"Andreas", "ig_andreas"_joaat},
	{"Ashley", "ig_ashley"_joaat},
	{"Ballasog", "ig_ballasog"_joaat},
	{"Bankman", "ig_bankman"_joaat},
	{"Barry", "ig_barry"_joaat},
	{"Barry_p", "ig_barry_p"_joaat},
	{"Bestmen", "ig_bestmen"_joaat},
	{"Beverly", "ig_beverly"_joaat},
	{"Beverly_p", "ig_beverly_p"_joaat},
	{"Brad", "ig_brad"_joaat},
	{"Bride", "ig_bride"_joaat},
	{"Car3guy1", "ig_car3guy1"_joaat},
	{"Car3guy2", "ig_car3guy2"_joaat},
	{"Casey", "ig_casey"_joaat},
	{"Chef", "ig_chef"_joaat},
	{"Chengsr", "ig_chengsr"_joaat},
	{"Chrisformage", "ig_chrisformage"_joaat},
	{"Clay", "ig_clay"_joaat},
	{"Claypain", "ig_claypain"_joaat},
	{"Cletus", "ig_cletus"_joaat},
	{"Dale", "ig_dale"_joaat},
	{"Davenorton", "ig_davenorton"_joaat},
	{"Denise", "ig_denise"_joaat},
	{"Devin", "ig_devin"_joaat},
	{"Dom", "ig_dom"_joaat},
	{"Dreyfuss", "ig_dreyfuss"_joaat},
	{"Drfriedlander", "ig_drfriedlander"_joaat},
	{"Fabien", "ig_fabien"_joaat},
	{"Fbisuit", "ig_fbisuit_01"_joaat},
	{"Floyd", "ig_floyd"_joaat},
	{"Groom", "ig_groom"_joaat},
	{"Hao", "ig_hao"_joaat},
	{"Hunter", "ig_hunter"_joaat},
	{"Janet", "ig_janet"_joaat},
	{"Jay_norris", "ig_jay_norris"_joaat},
	{"Jewelass", "ig_jewelass"_joaat},
	{"Jimmyboston", "ig_jimmyboston"_joaat},
	{"Jimmydisanto", "ig_jimmydisanto"_joaat},
	{"Joeminuteman", "ig_joeminuteman"_joaat},
	{"Johnnyklebitz", "ig_johnnyklebitz"_joaat},
	{"Josef", "ig_josef"_joaat},
	{"Josh", "ig_josh"_joaat},
	{"Kerrymcintosh", "ig_kerrymcintosh"_joaat},
	{"Lamardavis", "ig_lamardavis"_joaat},
	{"Lazlow", "ig_lazlow"_joaat},
	{"Lestercrest", "ig_lestercrest"_joaat},
	{"Lifeinvad", "ig_lifeinvad_01"_joaat},
	{"Lifeinvad", "ig_lifeinvad_02"_joaat},
	{"Magenta", "ig_magenta"_joaat},
	{"Manuel", "ig_manuel"_joaat},
	{"Marnie", "ig_marnie"_joaat},
	{"Maryann", "ig_maryann"_joaat},
	{"Maude", "ig_maude"_joaat},
	{"Michelle", "ig_michelle"_joaat},
	{"Milton", "ig_milton"_joaat},
	{"Molly", "ig_molly"_joaat},
	{"Mrk", "ig_mrk"_joaat},
	{"Mrsphillips", "ig_mrsphillips"_joaat},
	{"Mrs_thornhill", "ig_mrs_thornhill"_joaat},
	{"Natalia", "ig_natalia"_joaat},
	{"Nervousron", "ig_nervousron"_joaat},
	{"Nigel", "ig_nigel"_joaat},
	{"Old_man1a", "ig_old_man1a"_joaat},
	{"Old_man2", "ig_old_man2"_joaat},
	{"Omega", "ig_omega"_joaat},
	{"Oneil", "ig_oneil"_joaat},
	{"Orleans", "ig_orleans"_joaat},
	{"Ortega", "ig_ortega"_joaat},
	{"Paper", "ig_paper"_joaat},
	{"Patricia", "ig_patricia"_joaat},
	{"Priest", "ig_priest"_joaat},
	{"Prolsec", "ig_prolsec_02"_joaat},
	{"Gang", "ig_ramp_gang"_joaat},
	{"Hic", "ig_ramp_hic"_joaat},
	{"Hipster", "ig_ramp_hipster"_joaat},
	{"Mex", "ig_ramp_mex"_joaat},
	{"Roccopelosi", "ig_roccopelosi"_joaat},
	{"Russiandrunk", "ig_russiandrunk"_joaat},
	{"Screen_writer", "ig_screen_writer"_joaat},
	{"Siemonyetarian", "ig_siemonyetarian"_joaat},
	{"Solomon", "ig_solomon"_joaat},
	{"Stevehains", "ig_stevehains"_joaat},
	{"Stretch", "ig_stretch"_joaat},
	{"Talina", "ig_talina"_joaat},
	{"Tanisha", "ig_tanisha"_joaat},
	{"Taocheng", "ig_taocheng"_joaat},
	{"Taostranslator", "ig_taostranslator"_joaat},
	{"Taostranslator_p", "ig_taostranslator_p"_joaat},
	{"Tenniscoach", "ig_tenniscoach"_joaat},
	{"Terry", "ig_terry"_joaat},
	{"Tomepsilon", "ig_tomepsilon"_joaat},
	{"Tonya", "ig_tonya"_joaat},
	{"Tracydisanto", "ig_tracydisanto"_joaat},
	{"Trafficwarden", "ig_trafficwarden"_joaat},
	{"Tylerdix", "ig_tylerdix"_joaat},
	{"Wade", "ig_wade"_joaat},
	{"Zimbor", "ig_zimbor"_joaat},
	{"Deadhooker", "mp_f_deadhooker"_joaat},
	{"Misty", "mp_f_misty_01"_joaat},
	{"Stripperlite", "mp_f_stripperlite"_joaat},
	{"Pros", "mp_g_m_pros_01"_joaat},
	{"Mp_headtargets", "mp_headtargets"_joaat},
	{"Claude", "mp_m_claude_01"_joaat},
	{"Exarmy", "mp_m_exarmy_01"_joaat},
	{"Famdd", "mp_m_famdd_01"_joaat},
	{"Fibsec", "mp_m_fibsec_01"_joaat},
	{"Freemode", "mp_m_freemode_01"_joaat},
	{"Marston", "mp_m_marston_01"_joaat},
	{"Niko", "mp_m_niko_01"_joaat},
	{"Shopkeep", "mp_m_shopkeep_01"_joaat},
	{"Armoured", "mp_s_m_armoured_01"_joaat},
	{"Fembarber", "s_f_m_fembarber"_joaat},
	{"Maid", "s_f_m_maid_01"_joaat},
	{"Shop_high", "s_f_m_shop_high"_joaat},
	{"Sweatshop", "s_f_m_sweatshop_01"_joaat},
	{"Airhostess", "s_f_y_airhostess_01"_joaat},
	{"Bartender", "s_f_y_bartender_01"_joaat},
	{"Baywatch", "s_f_y_baywatch_01"_joaat},
	{"Cop", "s_f_y_cop_01"_joaat},
	{"Factory", "s_f_y_factory_01"_joaat},
	{"Hooker", "s_f_y_hooker_01"_joaat},
	{"Hooker", "s_f_y_hooker_02"_joaat},
	{"Hooker", "s_f_y_hooker_03"_joaat},
	{"Migrant", "s_f_y_migrant_01"_joaat},
	{"Movprem", "s_f_y_movprem_01"_joaat},
	{"Ranger", "s_f_y_ranger_01"_joaat},
	{"Scrubs", "s_f_y_scrubs_01"_joaat},
	{"Sheriff", "s_f_y_sheriff_01"_joaat},
	{"Shop_low", "s_f_y_shop_low"_joaat},
	{"Shop_mid", "s_f_y_shop_mid"_joaat},
	{"Stripperlite", "s_f_y_stripperlite"_joaat},
	{"Stripper", "s_f_y_stripper_01"_joaat},
	{"Stripper", "s_f_y_stripper_02"_joaat},
	{"Sweatshop", "s_f_y_sweatshop_01"_joaat},
	{"Ammucountry", "s_m_m_ammucountry"_joaat},
	{"Armoured", "s_m_m_armoured_01"_joaat},
	{"Armoured", "s_m_m_armoured_02"_joaat},
	{"Autoshop", "s_m_m_autoshop_01"_joaat},
	{"Autoshop", "s_m_m_autoshop_02"_joaat},
	{"Bouncer", "s_m_m_bouncer_01"_joaat},
	{"Chemsec", "s_m_m_chemsec_01"_joaat},
	{"Ciasec", "s_m_m_ciasec_01"_joaat},
	{"Cntrybar", "s_m_m_cntrybar_01"_joaat},
	{"Dockwork", "s_m_m_dockwork_01"_joaat},
	{"Doctor", "s_m_m_doctor_01"_joaat},
	{"Fiboffice", "s_m_m_fiboffice_01"_joaat},
	{"Fiboffice", "s_m_m_fiboffice_02"_joaat},
	{"Gaffer", "s_m_m_gaffer_01"_joaat},
	{"Gardener", "s_m_m_gardener_01"_joaat},
	{"Gentransport", "s_m_m_gentransport"_joaat},
	{"Hairdress", "s_m_m_hairdress_01"_joaat},
	{"Highsec", "s_m_m_highsec_01"_joaat},
	{"Highsec", "s_m_m_highsec_02"_joaat},
	{"Janitor", "s_m_m_janitor"_joaat},
	{"Lathandy", "s_m_m_lathandy_01"_joaat},
	{"Lifeinvad", "s_m_m_lifeinvad_01"_joaat},
	{"Linecook", "s_m_m_linecook"_joaat},
	{"Lsmetro", "s_m_m_lsmetro_01"_joaat},
	{"Mariachi", "s_m_m_mariachi_01"_joaat},
	{"Marine", "s_m_m_marine_01"_joaat},
	{"Marine", "s_m_m_marine_02"_joaat},
	{"Migrant", "s_m_m_migrant_01"_joaat},
	{"Zombie", "u_m_y_zombie_01"_joaat},
	{"Movprem", "s_m_m_movprem_01"_joaat},
	{"Paramedic", "s_m_m_paramedic_01"_joaat},
	{"Pilot", "s_m_m_pilot_01"_joaat},
	{"Pilot", "s_m_m_pilot_02"_joaat},
	{"Postal", "s_m_m_postal_01"_joaat},
	{"Postal", "s_m_m_postal_02"_joaat},
	{"Prisguard", "s_m_m_prisguard_01"_joaat},
	{"Scientist", "s_m_m_scientist_01"_joaat},
	{"Security", "s_m_m_security_01"_joaat},
	{"Snowcop", "s_m_m_snowcop_01"_joaat},
	{"Strperf", "s_m_m_strperf_01"_joaat},
	{"Strpreach", "s_m_m_strpreach_01"_joaat},
	{"Strvend", "s_m_m_strvend_01"_joaat},
	{"Trucker", "s_m_m_trucker_01"_joaat},
	{"Ups", "s_m_m_ups_01"_joaat},
	{"Ups", "s_m_m_ups_02"_joaat},
	{"Busker", "s_m_o_busker_01"_joaat},
	{"Airworker", "s_m_y_airworker"_joaat},
	{"Ammucity", "s_m_y_ammucity_01"_joaat},
	{"Armymech", "s_m_y_armymech_01"_joaat},
	{"Autopsy", "s_m_y_autopsy_01"_joaat},
	{"Barman", "s_m_y_barman_01"_joaat},
	{"Baywatch", "s_m_y_baywatch_01"_joaat},
	{"Blackops", "s_m_y_blackops_01"_joaat},
	{"Blackops", "s_m_y_blackops_02"_joaat},
	{"Busboy", "s_m_y_busboy_01"_joaat},
	{"Chef", "s_m_y_chef_01"_joaat},
	{"Clown", "s_m_y_clown_01"_joaat},
	{"Construct", "s_m_y_construct_01"_joaat},
	{"Construct", "s_m_y_construct_02"_joaat},
	{"Cop", "s_m_y_cop_01"_joaat},
	{"Dealer", "s_m_y_dealer_01"_joaat},
	{"Devinsec", "s_m_y_devinsec_01"_joaat},
	{"Dockwork", "s_m_y_dockwork_01"_joaat},
	{"Doorman", "s_m_y_doorman_01"_joaat},
	{"Dwservice", "s_m_y_dwservice_01"_joaat},
	{"Dwservice", "s_m_y_dwservice_02"_joaat},
	{"Factory", "s_m_y_factory_01"_joaat},
	{"Fireman", "s_m_y_fireman_01"_joaat},
	{"Garbage", "s_m_y_garbage"_joaat},
	{"Grip", "s_m_y_grip_01"_joaat},
	{"Hwaycop", "s_m_y_hwaycop_01"_joaat},
	{"Marine", "s_m_y_marine_01"_joaat},
	{"Marine", "s_m_y_marine_02"_joaat},
	{"Marine", "s_m_y_marine_03"_joaat},
	{"Mime", "s_m_y_mime"_joaat},
	{"Pestcont", "s_m_y_pestcont_01"_joaat},
	{"Pilot", "s_m_y_pilot_01"_joaat},
	{"Prismuscl", "s_m_y_prismuscl_01"_joaat},
	{"Ranger", "s_m_y_ranger_01"_joaat},
	{"Robber", "s_m_y_robber_01"_joaat},
	{"Sheriff", "s_m_y_sheriff_01"_joaat},
	{"Shop_mask", "s_m_y_shop_mask"_joaat},
	{"Strvend", "s_m_y_strvend_01"_joaat},
	{"Swat", "s_m_y_swat_01"_joaat},
	{"Uscg", "s_m_y_uscg_01"_joaat},
	{"Valet", "s_m_y_valet_01"_joaat},
	{"Waiter", "s_m_y_waiter_01"_joaat},
	{"Winclean", "s_m_y_winclean_01"_joaat},
	{"Xmech", "s_m_y_xmech_01"_joaat},
	{"Xmech", "s_m_y_xmech_02"_joaat},
	{"Corpse", "u_f_m_corpse_01"_joaat},
	{"Miranda", "u_f_m_miranda"_joaat},
	{"Promourn", "u_f_m_promourn_01"_joaat},
	{"Moviestar", "u_f_o_moviestar"_joaat},
	{"Prolhost", "u_f_o_prolhost_01"_joaat},
	{"Bikerchic", "u_f_y_bikerchic"_joaat},
	{"Comjane", "u_f_y_comjane"_joaat},
	{"Corpse", "u_f_y_corpse_01"_joaat},
	{"Corpse", "u_f_y_corpse_02"_joaat},
	{"Hotposh", "u_f_y_hotposh_01"_joaat},
	{"Jewelass", "u_f_y_jewelass_01"_joaat},
	{"Mistress", "u_f_y_mistress"_joaat},
	{"Poppymich", "u_f_y_poppymich"_joaat},
	{"Princess", "u_f_y_princess"_joaat},
	{"Spyactress", "u_f_y_spyactress"_joaat},
	{"Aldinapoli", "u_m_m_aldinapoli"_joaat},
	{"Bankman", "u_m_m_bankman"_joaat},
	{"Bikehire", "u_m_m_bikehire_01"_joaat},
	{"Fibarchitect", "u_m_m_fibarchitect"_joaat},
	{"Filmdirector", "u_m_m_filmdirector"_joaat},
	{"Glenstank", "u_m_m_glenstank_01"_joaat},
	{"Griff", "u_m_m_griff_01"_joaat},
	{"Jesus", "u_m_m_jesus_01"_joaat},
	{"Jewelsec", "u_m_m_jewelsec_01"_joaat},
	{"Jewelthief", "u_m_m_jewelthief"_joaat},
	{"Markfost", "u_m_m_markfost"_joaat},
	{"Partytarget", "u_m_m_partytarget"_joaat},
	{"Prolsec", "u_m_m_prolsec_01"_joaat},
	{"Promourn", "u_m_m_promourn_01"_joaat},
	{"Rivalpap", "u_m_m_rivalpap"_joaat},
	{"Spyactor", "u_m_m_spyactor"_joaat},
	{"Willyfist", "u_m_m_willyfist"_joaat},
	{"Finguru", "u_m_o_finguru_01"_joaat},
	{"Taphillbilly", "u_m_o_taphillbilly"_joaat},
	{"Tramp", "u_m_o_tramp_01"_joaat},
	{"Abner", "u_m_y_abner"_joaat},
	{"Antonb", "u_m_y_antonb"_joaat},
	{"Babyd", "u_m_y_babyd"_joaat},
	{"Baygor", "u_m_y_baygor"_joaat},
	{"Burgerdrug", "u_m_y_burgerdrug_01"_joaat},
	{"Chip", "u_m_y_chip"_joaat},
	{"Cyclist", "u_m_y_cyclist_01"_joaat},
	{"Fibmugger", "u_m_y_fibmugger_01"_joaat},
	{"Guido", "u_m_y_guido_01"_joaat},
	{"Gunvend", "u_m_y_gunvend_01"_joaat},
	{"Hippie", "u_m_y_hippie_01"_joaat},
	{"Militarybum", "u_m_y_militarybum"_joaat},
	{"Paparazzi", "u_m_y_paparazzi"_joaat},
	{"Party", "u_m_y_party_01"_joaat},
	{"Pogo", "u_m_y_pogo_01"_joaat},
	{"Prisoner", "u_m_y_prisoner_01"_joaat}
};

inline static std::pair<const char*, const char*> g_walk_map[] = {
	{"Generic Male", "move_m@generic"},
	{"Generic Female", "move_f@generic"},
	{"Cop", "move_cop@action"},
	{"Gangster", "move_m@gangster@generic"},
	{"Hipster", "move_m@hipster@a"},
	{"Hobo", "move_m@hobo@a"},
	{"Obese", "move_m@fat@a"},
	{"Lester", "move_lester_CaneUp"},
	{"Drunk", "move_m@drunk@a"},
	{"Moderate Drunk", "move_m@drunk@moderatedrunk"},
	{"Very Drunk", "move_m@drunk@verydrunk"},
	{"Sexy", "move_f@sexy@a"},
	{"Alien", "move_m@alien"},
	{"Business", "move_m@business@a"},
	{"Casual", "move_m@casual@a"},
	{"Clipboard", "move_m@clipboard"},
	{"Coward", "move_m@coward"},
	{"Burning", "move_m@fire"},
	{"Flee", "move_m@flee@a"},
	{"Hiking", "move_m@hiking"},
	{"Hurry", "move_m@hurry@a"},
	{"Injured", "move_injured_generic"},
	{"Intimidation", "move_m@intimidation@1h"},
	{"Muscular", "move_m@muscle@a"},
	{"Quick", "move_m@quick"},
	{"Sad", "move_m@sad@a"},
	{"Shady", "move_m@shadyped@a"},
	{"Shocked", "move_m@shocked@a"},
	{"Arrogant", "move_f@arrogant@a"},
	{"Handbag Walk", "move_f@handbag"},
	{"Heels", "move_f@heels@c"},
	{"Thug", "move_p_m_one"},
};
inline const char* g_wheel_type[] = {
"WHEEL_TYPE_SPORT",
"WHEEL_TYPE_MUSCLE",
"WHEEL_TYPE_LOWRIDER",
"WHEEL_TYPE_SUV",
"WHEEL_TYPE_OFFROAD",
"WHEEL_TYPE_TUNER",
"WHEEL_TYPE_BIKEWHEELS",
"WHEEL_TYPE_HIGHEND",
"WHEEL_TYPE_BENNYS_ORIGINAL",
"WHEEL_TYPE_BENNYS_BESPOKE",
"WHEEL_TYPE_OPEN_WHEEL",
"WHEEL_TYPE_STREET",
"WHEEL_TYPE_TRACK"

};
enum eVehicleModTypes 
{
	MOD_SPOILER,
	MOD_FRONTBUMPER,
	MOD_REARBUMPER,
	MOD_SIDESKIRT,
	MOD_EXHAUST,
	MOD_CHASSIS, //Or roll cage
	MOD_GRILLE,
	MOD_HOOD,
	MOD_FENDER,
	MOD_RIGHTFENDER,
	MOD_ROOF,
	MOD_ENGINE,
	MOD_BRAKES,
	MOD_TRANSMISSION,
	MOD_HORNS,
	MOD_SUSPENSION,
	MOD_ARMOR,
	MOD_UNK17 = 17,
	MOD_TURBO = 18,
	MOD_UNK19 = 19,
	MOD_TIRESMOKE = 20,
	MOD_UNK21 = 21,
	MOD_XENONLIGHTS = 22,
	MOD_FRONTWHEELS = 23,
	MOD_BACKWHEELS = 24, //Bikes only
	MOD_NITROUS = 17,
	MOD_TYRE_SMOKE = 20,
	MOD_XENON_LIGHTS = 22,

	// Benny's
	MOD_PLATEHOLDER = 25,
	MOD_VANITY_PLATES = 26,
	MOD_TRIM_DESIGN = 27,
	MOD_ORNAMENTS = 28,
	MOD_DASHBOARD = 29,
	MOD_DIAL = 30,
	MOD_DOOR_SPEAKER = 31,
	MOD_SEATS = 32,
	MOD_STEERINGWHEEL = 33,
	MOD_SHIFTER_LEAVERS = 34,
	MOD_PLAQUES = 35,
	MOD_SPEAKERS = 36, // might be 36
	MOD_TRUNK = 37,
	MOD_HYDRULICS = 38,
	MOD_ENGINE_BLOCK = 39,
	MOD_AIR_FILTER = 40,
	MOD_STRUTS = 41,
	MOD_ARCH_COVER = 42,
	MOD_AERIALS = 43,
	MOD_TRIM = 44,
	MOD_TANK = 45,
	MOD_WINDOWS = 46,
	MOD_UNK47 = 47,
	MOD_LIVERY = 48,

	MOD_SPECIAL_FRONT_RIMS = 62,
	MOD_SPECIAL_REAR_RIMS = 63,

	// custom
	MOD_NEON,
	MOD_HORN_STANDARD,
	MOD_HORN_MUSICAL,
	MOD_HORN_LOOP,
	MOD_WINDOWS_CUSTOM,
	MOD_PLATES
};